use std::collections::HashMap;
use std::sync::Arc;

use super::FinalizedSlotPolicy;
use crate::state::traits::PinnedCacheAccessor;
use crate::ConcurrentStateCheckpoint;
use crate::GasMeteringError;
use concread::hashmap::HashMapReadTxn;
use sov_metrics::{StateAccessMetric, StateMetrics};
use sov_rollup_interface::common::{SlotNumber, VisibleSlotNumber};
use sov_state::pinned_cache::PinnedCache;
use sov_state::sequencer_state::MaybePresentValue;
use sov_state::StateGetter;
use sov_state::{
    namespaces, CompileTimeNamespace, EventContainer, Namespace, NativeStorage, SlotKey, SlotValue,
    Storage, TypeErasedEvent,
};

use super::temp_cache::{CacheLookup, TempCache};
use super::{BorshSerializedSize, UniversalStateAccessor};
use crate::capabilities::{KernelWithSlotMapping, RollupHeight};
use crate::gas::GasArray;
use crate::state::accessors::internals::AccessoryWrite;
use crate::state::traits::PerBlockCache;
use crate::{BasicGasMeter, Gas, GasMeter, GetGasPrice, ProvableStateReader, Spec, VersionReader};

fn get_slot_number(visible_slot_number: Option<VisibleSlotNumber>) -> Option<SlotNumber> {
    // This TODO is not a security risk.
    // TODO: This is an ugly hack to work around the dual use of self.visible_slot_number.
    // We use it inside `VersionReader` to determine what state the accessor is allowed to access (which requires it to be set)
    // but also here to determine what state version to query *from disk*. Unfortunately, those two numbers don't always agree *during initialization*,
    // so we have to use u64::MAX as a marker value to say "the accessor should be allowed to access any value and should use the latest info from storage as necessary."
    // We should separate out the notion of permissions from the notion of what state version to query from disk.
    if let Some(num) = visible_slot_number {
        if num.get() != u64::MAX {
            Some(num.as_true())
        } else {
            None
        }
    } else {
        None
    }
}

impl<S: Spec> UniversalStateAccessor for ApiStateAccessor<S> {
    fn get_size(
        &mut self,
        namespace: sov_state::Namespace,
        key: &SlotKey,
        _metric: &mut StateAccessMetric,
    ) -> Option<u32> {
        let is_archival_query = self.safe_true_slot_number_to_use.is_some();

        let result = match namespace {
            Namespace::User => {
                if let Some(number) = self.safe_true_slot_number_to_use {
                    // If we're doing an archival query, we can just use the historical storage API on `ProvableStorageCache`
                    self.get_archival_from_user_storage(key, Some(number))
                        .map(|v| v.map(|v| v.size()))
                } else {
                    // Otherwise we're doing a `current_state` query, so we need to use the API which is also aware of the intermediate state
                    // generated by the sequencer.
                    Ok(self.get_from_user_storage(key).map(|v| v.size()))
                }
            }
            Namespace::Kernel => {
                if is_archival_query {
                    // If we're doing an archival query, we can just use the historical storage API on `ProvableStorageCache`
                    self.get_archival_from_kernel_storage(
                        key,
                        get_slot_number(self.visible_slot_number),
                    )
                    .map(|v| v.map(|v| v.size()))
                } else {
                    // Otherwise we're doing a `current_state` query, so we need to use the API which is also aware of the intermediate state
                    // generated by the sequencer.
                    Ok(self.get_from_kernel_storage(key).map(|v| v.size()))
                }
            }
            Namespace::Accessory => match self.local_accessory_writes.get(key).cloned() {
                Some(write) => Ok(write.value.as_ref().map(|v| v.size())),
                None => {
                    if is_archival_query {
                        // For archival queries, we always use the storage API
                        self.get_archival_from_accessory_storage(
                            key,
                            self.safe_true_slot_number_to_use,
                        )
                        .map(|v| v.map(|v| v.size()))
                    } else {
                        Ok(self.get_from_accessory_storage(key).map(|v| v.size()))
                    }
                }
            },
        };
        match result {
            Ok(value) => value,
            Err(e) => {
                tracing::debug!(error = ?e, queried_slot_number = ?self.safe_true_slot_number_to_use, "Error encountered while fetching data from ApiStateAccessor");
                self.encountered_pruning_error = Some(e);
                None
            }
        }
    }

    fn get_value(
        &mut self,
        namespace: sov_state::Namespace,
        key: &SlotKey,
        _metric: &mut StateAccessMetric,
    ) -> Option<SlotValue> {
        let is_archival_query = self.safe_true_slot_number_to_use.is_some();
        // For the user state, we use the self.safe_true_slot_number_to_use canary to determine if we're doing an archival query
        // If we are, use the appropriate API on `ProvableStorageCache`
        let result = match namespace {
            Namespace::User => {
                if let Some(number) = self.safe_true_slot_number_to_use {
                    self.get_archival_from_user_storage(key, Some(number))
                } else {
                    // Otherwise we're doing a `current_state` query, so we need to use the API which is also aware of the intermediate state
                    // generated by the sequencer.
                    Ok(self.get_from_user_storage(key))
                }
            }
            // For the kernel state, we also use the self.safe_true_slot_number_to_use canary to determine if we're doing an archival query
            // If so, use the appropriate API on `ProvableStorageCache`
            Namespace::Kernel => {
                if is_archival_query {
                    self.get_archival_from_kernel_storage(
                        key,
                        get_slot_number(self.visible_slot_number),
                    )
                } else {
                    // Otherwise we're doing a `current_state` query, so we need to use the API which is also aware of the intermediate state
                    // generated by the sequencer.
                    Ok(self.get_from_kernel_storage(key))
                }
            }
            Namespace::Accessory => match self.local_accessory_writes.get(key).cloned() {
                Some(write) => Ok(write.value),
                None => {
                    // For archival queries, we always use the storage API
                    if is_archival_query {
                        self.get_archival_from_accessory_storage(
                            key,
                            self.safe_true_slot_number_to_use,
                        )
                    } else {
                        // For current state queries, we use the intermediate state if it's available
                        Ok(self.get_from_accessory_storage(key))
                    }
                }
            },
        };
        match result {
            Ok(value) => value,
            Err(e) => {
                tracing::debug!(error = ?e, queried_slot_number = ?self.safe_true_slot_number_to_use, "Error encountered while fetching data from ApiStateAccessor");
                self.encountered_pruning_error = Some(e);
                None
            }
        }
    }

    fn set_value(&mut self, namespace: sov_state::Namespace, key: &SlotKey, value: SlotValue) {
        // The rollup height is only used for pruning the sequencer state checkpoint - which is irrelelvant for the API. So we use a dummy value.
        match namespace {
            Namespace::User => {
                self.local_user_writes.insert(key.clone(), Some(value));
            }
            Namespace::Kernel => {
                self.local_kernel_writes.insert(key.clone(), Some(value));
            }
            Namespace::Accessory => {
                self.local_accessory_writes
                    .insert(key.clone(), AccessoryWrite::new(Some(value)));
            }
        }
    }

    fn delete_value(&mut self, namespace: sov_state::Namespace, key: &SlotKey) {
        // The rollup height is only used for pruning the sequencer state checkpoint - which is irrelelvant for the API. So we use a dummy value.
        match namespace {
            Namespace::User => {
                self.local_user_writes.insert(key.clone(), None);
            }
            Namespace::Kernel => {
                self.local_kernel_writes.insert(key.clone(), None);
            }
            Namespace::Accessory => {
                self.local_accessory_writes
                    .insert(key.clone(), AccessoryWrite::new(None));
            }
        }
    }
}

#[derive(Clone, Debug, Copy, PartialEq, Eq, Hash)]
pub(crate) enum StateToAccess {
    RollupHeight(RollupHeight),
    TrueSlotNumber(
        SlotNumber,
        // We always cache the rollup height for the requested slot number during initialization. However,
        // it can be `None` while initialization is still in progress.
        Option<RollupHeight>,
    ),
}

#[derive(derive_more::Debug, Clone)]
struct CheckpointAndReadTxn<S: Spec> {
    // IMPORTANT: Do not re-order the checkpoint before the read_txn - otherwise the read_txn will potentially  be invalidated for a split second on drop.
    #[debug(skip)]
    read_txn: Arc<HashMapReadTxn<'static, (SlotKey, Namespace), Option<SlotValue>>>,
    // IMPORTANT: Do not re-order the checkpoint before the read_txn - otherwise the read_txn will potentially  be invalidated for a split second on drop.
    // This is undefined behavior
    state_checkpoint: Arc<ConcurrentStateCheckpoint<S>>,
}

impl<S: Spec> CheckpointAndReadTxn<S> {
    pub fn new(state_checkpoint: Arc<ConcurrentStateCheckpoint<S>>) -> Self {
        Self {
            read_txn: Arc::new(unsafe { Self::lengthen_lifetime(state_checkpoint.writes.read()) }),
            state_checkpoint,
        }
    }

    /// A very, very unsafe function that lengthens the lifetime of a read transaction to `'static`.
    ///
    /// We use this function because ApiStateAccessor has to be 'static for compatibility with Axum/Tokio.
    /// Our use of this function is sound because we only use it on Arc<ConcurrentStateCheckpoint<S>> while we're one of the holders of the Arc,
    /// so the resulting read txn is guaranteed to be dropped before the Concread::HashMap is.
    unsafe fn lengthen_lifetime(
        read_txn: HashMapReadTxn<'_, (SlotKey, Namespace), Option<SlotValue>>,
    ) -> HashMapReadTxn<'static, (SlotKey, Namespace), Option<SlotValue>> {
        std::mem::transmute(read_txn)
    }
}
/// A [`crate::StateReaderAndWriter`] designed for use within REST APIs and JSON-RPC.
///
/// It can read and write accessory data as well as "user" and "kernel" data.
#[derive(derive_more::Debug)]
pub struct ApiStateAccessor<S: Spec> {
    #[debug(skip)]
    witness: <<S as Spec>::Storage as Storage>::Witness,
    events: Vec<TypeErasedEvent>,
    gas_meter: BasicGasMeter<S>,
    local_kernel_writes: HashMap<SlotKey, Option<SlotValue>>,
    local_user_writes: HashMap<SlotKey, Option<SlotValue>>,
    local_accessory_writes: HashMap<SlotKey, AccessoryWrite>,
    uncommitted_changes: Option<Box<dyn StateGetter>>,
    temp_cache: TempCache,
    checkpoint_and_read_txn: CheckpointAndReadTxn<S>,
    #[debug(skip)]
    kernel: Arc<dyn KernelWithSlotMapping<S>>,
    // The state requested by the user - either a `RollupHeight` or a `SlotNumber`
    state_to_access: StateToAccess,
    // The visible slot number is always stored in the accessor by the time initialization is complete.
    // Unfortunately, we need to run one query using the accessor in order to determine the correct visible slot number,
    // so we can't make this field non-optional.
    visible_slot_number: Option<VisibleSlotNumber>,
    // The true slot number to use for user/accessory queries. This need not correspond exactly the accessor's
    // rollup height (if present) but it must be older than the N+1th rollup height.
    //
    // Suppose we have the following rollup heights:
    //  height:           1 -> 2 -> 3 -> 4 -> 5
    //  true_slot_number: 1 -> 4 -> 7 -> 10 -> 13
    //
    // Then a safe true slot number to use for user/accessory queries with rollup height 4 is 7, 8, 9, or 10 since all of these numbers
    // will cause any state *before* 4 to be visible. (Assume that the state checkpoint the accessor is based on contains all the state *of* 4 in memory)
    safe_true_slot_number_to_use: Option<SlotNumber>,
    encountered_pruning_error: Option<anyhow::Error>,
    pub(crate) metrics: StateMetrics,
}

impl<S: Spec> PerBlockCache for ApiStateAccessor<S> {
    fn get_cached<T: 'static + Send + Sync>(&self, slot_key: Option<SlotKey>) -> Option<&T> {
        if let CacheLookup::Hit(v) = self.temp_cache.get::<T>(slot_key) {
            v
        } else {
            None
        }
    }

    fn put_cached<T: 'static + Send + Sync + BorshSerializedSize>(
        &mut self,
        slot_key: Option<SlotKey>,
        value: T,
    ) {
        self.temp_cache.set(slot_key, value);
    }

    fn delete_cached<T: 'static + Send + Sync>(&mut self, slot_key: Option<SlotKey>) {
        self.temp_cache.delete::<T>(slot_key);
    }

    fn update_cache_with(&mut self, other: TempCache) {
        self.temp_cache.update_with(other);
    }
}

impl<S: Spec> PinnedCacheAccessor<S> for ApiStateAccessor<S> {
    fn pinned_cache_mut(&mut self) -> Option<&mut PinnedCache> {
        None
    }
    fn storage(&self) -> &S::Storage {
        self.checkpoint_and_read_txn.state_checkpoint.storage()
    }
}

#[cfg(feature = "native")]
const _: () = {
    use sov_state::{NativeStorage, ProvableCompileTimeNamespace, StorageProof};

    use crate::{ProvenStateAccessor, StateReaderAndWriter};

    impl<N, S: Spec> ProvenStateAccessor<N> for ApiStateAccessor<S>
    where
        N: ProvableCompileTimeNamespace,
        S::Storage: NativeStorage,
        ApiStateAccessor<S>: StateReaderAndWriter<N>,
    {
        type Proof = <<S as Spec>::Storage as Storage>::Proof;

        fn get_global_latest_with_proof(
            &mut self,
            key: SlotKey,
        ) -> Option<StorageProof<Self::Proof>> {
            match self.storage().get_with_proof::<N>(key) {
                Ok(storage_proof) => Some(storage_proof.0),
                Err(err) => {
                    tracing::error!(error = ?err, "Error requesting storage proof");
                    None
                }
            }
        }
    }
};

impl<S: Spec> GasMeter for ApiStateAccessor<S> {
    type Spec = S;

    fn try_as_basic_gas_meter(&mut self) -> Option<&mut BasicGasMeter<Self::Spec>> {
        Some(&mut self.gas_meter)
    }

    fn charge_gas(
        &mut self,
        amount: <Self::Spec as Spec>::Gas,
    ) -> anyhow::Result<(), GasMeteringError<<Self::Spec as Spec>::Gas>> {
        self.gas_meter.charge_gas(amount)
    }

    fn charge_linear_gas(
        &mut self,
        amount: <Self::Spec as Spec>::Gas,
        parameter: u32,
    ) -> anyhow::Result<(), GasMeteringError<<Self::Spec as Spec>::Gas>> {
        self.gas_meter.charge_linear_gas(amount, parameter)
    }
}

impl<S: Spec> GetGasPrice for ApiStateAccessor<S> {
    type Spec = S;
    fn gas_price(&self) -> <S::Gas as Gas>::Price {
        self.gas_meter.gas_price
    }
}

impl<S: Spec> EventContainer for ApiStateAccessor<S> {
    fn add_event<E: 'static + core::marker::Send + core::marker::Sync>(
        &mut self,
        event_key: &str,
        event: E,
    ) {
        self.events.push(TypeErasedEvent::new(event_key, event));
    }

    fn add_type_erased_event(&mut self, event: TypeErasedEvent) {
        self.events.push(event);
    }
}

impl<S: Spec> ApiStateAccessor<S> {
    fn get_from_user_storage(&self, key: &SlotKey) -> Option<SlotValue> {
        if let Some(entry) = self.local_user_writes.get(key) {
            return entry.clone();
        }

        if let Some(entry) = self
            .checkpoint_and_read_txn
            .read_txn
            .get(&(key.clone(), Namespace::User))
        {
            return entry.clone();
        }

        if let Some(changes) = self.uncommitted_changes.as_ref() {
            if let MaybePresentValue::Present(entry) = changes.get(Namespace::User, key) {
                return entry;
            }
        }

        self.checkpoint_and_read_txn
            .state_checkpoint
            .storage()
            .get::<namespaces::User>(key, &self.witness)
    }

    fn get_from_kernel_storage(&self, key: &SlotKey) -> Option<SlotValue> {
        if let Some(entry) = self.local_kernel_writes.get(key) {
            return entry.clone();
        }

        if let Some(entry) = self
            .checkpoint_and_read_txn
            .read_txn
            .get(&(key.clone(), Namespace::Kernel))
        {
            return entry.clone();
        }

        if let Some(changes) = self.uncommitted_changes.as_ref() {
            if let MaybePresentValue::Present(entry) = changes.get(Namespace::Kernel, key) {
                return entry;
            }
        }

        self.checkpoint_and_read_txn
            .state_checkpoint
            .storage()
            .get::<namespaces::Kernel>(key, &self.witness)
    }

    fn get_from_accessory_storage(&self, key: &SlotKey) -> Option<SlotValue> {
        if let Some(write) = self.local_accessory_writes.get(key) {
            return write.value.clone();
        }

        if let Some(write) = self
            .checkpoint_and_read_txn
            .read_txn
            .get(&(key.clone(), Namespace::Accessory))
        {
            return write.clone();
        }

        if let Some(changes) = self.uncommitted_changes.as_ref() {
            if let MaybePresentValue::Present(entry) = changes.get(Namespace::Accessory, key) {
                return entry;
            }
        }

        self.checkpoint_and_read_txn
            .state_checkpoint
            .storage()
            .get_accessory(key)
    }

    fn get_archival_from_user_storage(
        &mut self,
        key: &SlotKey,
        version: Option<SlotNumber>,
    ) -> anyhow::Result<Option<SlotValue>> {
        // First, check if the user has written this value. This allows users to write during eth_call even if they're reading historical state.
        // IMPORTANT: Note that we do *not* read from the state checkpoint during archival queries (it's Arc'd and may contain
        // unrelated data from the current state). However, reading from uncommitted_changes is safe because build_archival_state
        // filters them via ignore_changes_after_height(height) to only contain data at heights <= the requested height.
        if let Some(entry) = self.local_user_writes.get(key) {
            return Ok(entry.clone());
        }
        if let Some(changes) = self.uncommitted_changes.as_ref() {
            if let MaybePresentValue::Present(entry) = changes.get(Namespace::User, key) {
                return Ok(entry);
            }
        }

        self.checkpoint_and_read_txn
            .state_checkpoint
            .storage()
            .get_historical::<namespaces::User>(key, version, &self.witness)
    }

    fn get_archival_from_kernel_storage(
        &mut self,
        key: &SlotKey,
        version: Option<SlotNumber>,
    ) -> anyhow::Result<Option<SlotValue>> {
        // First, check if the kernel has written this value. This allows users to write during eth_call even if they're reading historical state.
        // IMPORTANT: Note that we do *not* read from the state checkpoint during archival queries (it's Arc'd and may contain
        // unrelated data from the current state). However, reading from uncommitted_changes is safe because build_archival_state
        // filters them via ignore_changes_after_height(height) to only contain data at heights <= the requested height.
        if let Some(entry) = self.local_kernel_writes.get(key) {
            return Ok(entry.clone());
        }
        if let Some(changes) = self.uncommitted_changes.as_ref() {
            if let MaybePresentValue::Present(entry) = changes.get(Namespace::Kernel, key) {
                return Ok(entry);
            }
        }

        self.checkpoint_and_read_txn
            .state_checkpoint
            .storage()
            .get_historical::<namespaces::Kernel>(key, version, &self.witness)
    }

    fn get_archival_from_accessory_storage(
        &mut self,
        key: &SlotKey,
        version: Option<SlotNumber>,
    ) -> anyhow::Result<Option<SlotValue>> {
        // First, check if the accessory has written this value. This allows users to write during eth_call even if they're reading historical state.
        if let Some(write) = self.local_accessory_writes.get(key) {
            return Ok(write.value.clone());
        }

        if let Some(changes) = self.uncommitted_changes.as_ref() {
            if let MaybePresentValue::Present(entry) = changes.get(Namespace::Accessory, key) {
                return Ok(entry);
            }
        }

        self.checkpoint_and_read_txn
            .state_checkpoint
            .storage()
            .get_accessory_historical(key, version)
    }
}

/// An error that can occur when creating an [`ApiStateAccessor`].
#[derive(Debug, thiserror::Error, Clone, PartialEq, Eq)]
pub enum ApiStateAccessorError {
    /// The requested height is not accessible.
    #[error("Impossible to get the rollup state at the specified height. The requested height may have been pruned, or it may be in the future. Please ensure you have queried the correct height.")]
    HeightNotAccessible,
}

impl<S: Spec + 'static> ApiStateAccessor<S> {
    /// Creates a new [`ApiStateAccessor`] from a [`StateCheckpoint`] with a gas price of zero at the [`StateCheckpoint::rollup_height_to_access`].
    pub fn new(
        state_checkpoint: Arc<ConcurrentStateCheckpoint<S>>,
        kernel: Arc<dyn KernelWithSlotMapping<S>>,
    ) -> Self {
        let rollup_height = state_checkpoint.rollup_height_to_access();
        Self::new_with_price_and_state_to_access(
            state_checkpoint,
            kernel,
            StateToAccess::RollupHeight(rollup_height),
            <S::Gas as Gas>::Price::ZEROED,
        )
        .expect("Creating an ApiStateCheckpoint without specifying a height is infallible")
    }

    /// Creates a new [`ApiStateAccessor`] which queries all state at the provided slot number.
    pub fn new_archival_with_true_slot_number(
        state_checkpoint: Arc<ConcurrentStateCheckpoint<S>>,
        kernel: Arc<dyn KernelWithSlotMapping<S>>,
        slot_number: SlotNumber,
    ) -> Result<Self, ApiStateAccessorError> {
        let uncommitted_changes = state_checkpoint
            .uncommitted_changes
            .as_ref()
            .map(|c| c.box_clone());
        Self::build_archival_state(
            state_checkpoint,
            uncommitted_changes,
            kernel,
            StateToAccess::TrueSlotNumber(slot_number, None),
        )
    }

    /// Creates a fully initialized [`ApiStateAccessor`] from a [`StateCheckpoint`] and a [`RollupHeight`], if the requested
    /// height is available in storage.
    ///
    /// ## Important
    /// Note that archival state is only available *after* the requested height has been processed by the node. In other words,
    /// state that is *only* soft-confirmed is not available for archival queries.
    pub fn new_archival(
        state_checkpoint: Arc<ConcurrentStateCheckpoint<S>>,
        kernel: Arc<dyn KernelWithSlotMapping<S>>,
        height: RollupHeight,
    ) -> Result<Self, ApiStateAccessorError> {
        let uncommitted_changes = state_checkpoint
            .uncommitted_changes
            .as_ref()
            .map(|c| c.box_clone());
        Self::build_archival_state(
            state_checkpoint,
            uncommitted_changes,
            kernel,
            StateToAccess::RollupHeight(height),
        )
    }

    /// Creates a new [`ApiStateAccessor`] from a [`StateCheckpoint`] with a gas price of zero at the [`StateCheckpoint::rollup_height_to_access`].
    pub fn new_with_true_slot_number_dangerous(
        state_checkpoint: Arc<ConcurrentStateCheckpoint<S>>,
        kernel: Arc<dyn KernelWithSlotMapping<S>>,
        slot_number: SlotNumber,
    ) -> Result<Self, ApiStateAccessorError> {
        Self::new_with_price_and_state_to_access(
            state_checkpoint,
            kernel,
            StateToAccess::TrueSlotNumber(slot_number, None),
            <S::Gas as Gas>::Price::ZEROED,
        )
    }

    /// Converts this [`ApiStateAccessor`] into a [`MeteredApiStateAccessor`], allowing it to be used in authenticator methods.
    pub fn to_provable_reader(self) -> MeteredApiStateAccessor<S> {
        MeteredApiStateAccessor {
            api_state_accessor: self,
        }
    }

    /// A specialized constructor for use in sov-test-utils. This constructor matches the unusual semantic of our testing framework, which expects to see
    /// the *next* visible slot number with the *current* rollup height in the accessor as soon as the slot finishes executing.
    ///
    /// In actual execution, this semantic is not needed because the time between the end of slot N and the start of slot N+1 is neglible. Unfortunately,
    /// our tests are written assuming that all assertions will execute during this miniscule instant of time, so we have to accommodate it for now.
    #[cfg(feature = "test-utils")]
    pub fn new_with_price_and_heights(
        state_checkpoint: Arc<ConcurrentStateCheckpoint<S>>,
        kernel: Arc<dyn KernelWithSlotMapping<S>>,
        rollup_height: RollupHeight,
        visible_slot_number: VisibleSlotNumber,
        gas_price: <S::Gas as Gas>::Price,
    ) -> Result<Self, ApiStateAccessorError> {
        let mut accessor = Self::new_with_price_and_state_to_access(
            state_checkpoint,
            kernel,
            StateToAccess::RollupHeight(rollup_height),
            gas_price,
        )?;
        accessor.visible_slot_number = Some(visible_slot_number);
        Ok(accessor)
    }

    /// Creates a new [`ApiStateAccessor`] that *queries all state at the provided slot number, regardless of whether that slot number is visible*. This should only be used
    /// when the semantics of the call necessitate it. If you're unsure, use [`ApiStateAccessor::new_archival`] and provide a rollup height instead.
    pub fn new_with_price_and_slot_number_dangerous(
        state_checkpoint: Arc<ConcurrentStateCheckpoint<S>>,
        kernel: Arc<dyn KernelWithSlotMapping<S>>,
        slot_number: SlotNumber,
        gas_price: <S::Gas as Gas>::Price,
    ) -> Result<Self, ApiStateAccessorError> {
        Self::new_with_price_and_state_to_access(
            state_checkpoint,
            kernel,
            StateToAccess::TrueSlotNumber(slot_number, None),
            gas_price,
        )
    }

    /// Creates a new [`ApiStateAccessor`] from a [`StateCheckpoint`] with the provided gas price.
    fn new_with_price_and_state_to_access(
        state_checkpoint: Arc<ConcurrentStateCheckpoint<S>>,
        kernel: Arc<dyn KernelWithSlotMapping<S>>,
        state_to_access: StateToAccess,
        gas_price: <S::Gas as Gas>::Price,
    ) -> Result<Self, ApiStateAccessorError> {
        let gas_meter = BasicGasMeter::new_api(gas_price);
        let uncommitted_changes = state_checkpoint
            .uncommitted_changes
            .as_ref()
            .map(|g| g.box_clone());
        let checkpoint_and_read_txn = CheckpointAndReadTxn::new(state_checkpoint);

        let mut out = Self {
            uncommitted_changes,
            witness: Default::default(),
            gas_meter,
            events: Vec::new(),
            temp_cache: TempCache::new(),
            checkpoint_and_read_txn,
            local_kernel_writes: HashMap::new(),
            local_user_writes: HashMap::new(),
            local_accessory_writes: HashMap::new(),
            kernel: kernel.clone(),
            state_to_access,
            visible_slot_number: None,
            safe_true_slot_number_to_use: None,
            encountered_pruning_error: None,
            metrics: StateMetrics::default(),
        };

        (out.safe_true_slot_number_to_use) = match state_to_access {
            // The current slot may not be stored in the `true_slot_number_at_historical_height` map, so we use the previous slot number.
            StateToAccess::RollupHeight(rollup_height) => {
                // If this is a slot that has already been executed, we know the correct true slot number. Use that.
                kernel.true_slot_number_at_historical_height(rollup_height, &mut out)
            }
            StateToAccess::TrueSlotNumber(slot_number, _) => Some(slot_number),
        };

        if let StateToAccess::TrueSlotNumber(slot_number, _) = state_to_access {
            let Some(rollup_height) =
                kernel.true_slot_number_to_rollup_height(slot_number, &mut out)
            else {
                return Err(ApiStateAccessorError::HeightNotAccessible);
            };
            out.state_to_access = StateToAccess::TrueSlotNumber(slot_number, Some(rollup_height));
        }

        let Some(visible_slot_number) = out.lookup_visible_slot_number() else {
            return Err(ApiStateAccessorError::HeightNotAccessible);
        };

        out.visible_slot_number = Some(visible_slot_number);

        Ok(out)
    }

    fn get_uninitialized_empty_accessor(
        state_checkpoint: Arc<ConcurrentStateCheckpoint<S>>,
        kernel: Arc<dyn KernelWithSlotMapping<S>>,
        state_to_access: StateToAccess,
    ) -> Self {
        let uncommitted_changes = state_checkpoint
            .uncommitted_changes
            .as_ref()
            .map(|g| g.box_clone());
        let checkpoint_and_read_txn = CheckpointAndReadTxn::new(state_checkpoint);
        let gas_meter = BasicGasMeter::new_api(<S::Gas as Gas>::Price::ZEROED);
        Self {
            events: Vec::new(),
            gas_meter,
            uncommitted_changes,
            checkpoint_and_read_txn,
            witness: Default::default(),
            local_kernel_writes: HashMap::new(),
            local_user_writes: HashMap::new(),
            local_accessory_writes: HashMap::new(),
            temp_cache: TempCache::new(),
            kernel: kernel.clone(),
            state_to_access,
            safe_true_slot_number_to_use: None,
            // We use MAX here to indicate that the accessor should be allowed to access any value. This is necessary because of the fundamental
            // permissions vs state confusion in our current design of VersionReader - see the comment inline in get_cached for more details.
            visible_slot_number: Some(VisibleSlotNumber::MAX),
            encountered_pruning_error: None,
            metrics: StateMetrics::default(),
        }
    }

    fn lookup_visible_slot_number(&mut self) -> Option<VisibleSlotNumber> {
        match self.state_to_access {
            StateToAccess::RollupHeight(rollup_height) => self
                .kernel
                .clone()
                .rollup_height_to_visible_slot_number(rollup_height, self),
            StateToAccess::TrueSlotNumber(slot_number, _) => {
                let visible_slot_number = VisibleSlotNumber::new_dangerous(slot_number.get());
                Some(visible_slot_number)
            }
        }
    }

    fn clear_caches(&mut self) {
        self.local_kernel_writes = HashMap::new();
        self.local_user_writes = HashMap::new();
        self.local_accessory_writes = HashMap::new();
    }

    /// Sets the gas price for the accessor.
    pub fn set_gas_price(&mut self, gas_price: <S::Gas as Gas>::Price) {
        self.gas_meter.gas_price = gas_price;
    }

    fn build_archival_state(
        state_checkpoint: Arc<ConcurrentStateCheckpoint<S>>,
        uncommitted_changes: Option<Box<dyn StateGetter>>,
        kernel: Arc<dyn KernelWithSlotMapping<S>>,
        height: StateToAccess,
    ) -> Result<Self, ApiStateAccessorError> {
        let latest_true_slot_number = state_checkpoint.storage().latest_version();
        let mut state = ApiStateAccessor::get_uninitialized_empty_accessor(
            state_checkpoint,
            kernel.clone(),
            height,
        );
        state.uncommitted_changes = uncommitted_changes;
        let true_slot_number = match height {
            // If the caller provided a rollup height, find the associated true slot number.
            StateToAccess::RollupHeight(height) => {
                if let Some(true_slot_number) =
                    kernel.true_slot_number_at_historical_height(height, &mut state)
                {
                    true_slot_number
                } else if let Some(max_height) = state
                    .uncommitted_changes
                    .as_ref()
                    .and_then(|c| c.latest_rollup_height())
                {
                    // If the requested height is greater than our uncommitted changes, we can't access it.
                    if max_height < height {
                        return Err(ApiStateAccessorError::HeightNotAccessible);
                    }
                    // Use our latest slot number from storage as a safe commit.
                    // (Anything not already in storage by that point will be in the uncommitted changes,
                    // which are pruned to the requested height below.)
                    latest_true_slot_number
                } else if height == kernel.current_rollup_height(&mut state) {
                    // There's a tricky case here where the height exists in storage but the true slot number is not available via the kernel yet.
                    // This is because the true slot number mapping is updated at the beginning of the next slot, but the rest of the values are written
                    // at the end of the current slot.
                    //
                    // Since the ApiStateAccessor has empty caches right now, we can check if we're in this case by checking whether the requested height is equal to the current rollup height
                    // as reported by the kernel. (Recall that, since the caches are empty, the "current_rollup_height" value reported by the kernel is the value stored at S::Storage::latest_version.)
                    latest_true_slot_number
                } else {
                    return Err(ApiStateAccessorError::HeightNotAccessible);
                }
            }
            StateToAccess::TrueSlotNumber(slot_number, _) => {
                if slot_number > latest_true_slot_number {
                    return Err(ApiStateAccessorError::HeightNotAccessible);
                }
                slot_number
            }
        };

        // If the caller provided a true slot number, find the associated rollup height.
        let rollup_height = match height {
            StateToAccess::RollupHeight(rollup_height)
            | StateToAccess::TrueSlotNumber(_, Some(rollup_height)) => rollup_height,
            StateToAccess::TrueSlotNumber(slot_number, None) => {
                let result = kernel.true_slot_number_to_rollup_height(slot_number, &mut state);
                if state.encountered_pruning_error.is_some() {
                    return Err(ApiStateAccessorError::HeightNotAccessible);
                }
                result.unwrap_or_else(|| panic!("Visible slot number not available for slot_number {slot_number}, but that slot exists in storage. This is a bug. Please report it."))
            }
        };
        // Prune uncommitted changes to only contain data at heights <= the requested rollup height.
        // This ensures archival reads never return values from newer uncommitted blocks.
        if let Some(c) = state.uncommitted_changes.as_mut() {
            c.ignore_changes_after_height(rollup_height);
        }
        // Use the slot number to find the visible slot number.
        let result = kernel.visible_slot_number_at(true_slot_number, &mut state);

        let Some(visible_slot_number) = result else {
            panic!("Visible slot number not available at slot number {true_slot_number}, but that height exist in storage. This is a bug. Please report it.");
        };
        // Use the rollup height to find the base fee per gas.
        let result = kernel.base_fee_per_gas_at(rollup_height, &mut state);
        let Some(base_fee_per_gas) = result else {
            panic!("Base fee per gas not available at height {rollup_height}, but that height exist in storage. This is a bug. Please report it.");
        };
        state.visible_slot_number = Some(visible_slot_number);
        state.safe_true_slot_number_to_use = Some(true_slot_number);
        state.set_gas_price(base_fee_per_gas);
        // Run a test query at the requested height to ensure that the state is accessible.
        let test_key = SlotKey::from_slice(b"test-key");
        let _test_query_result = state.get_value(
            namespaces::User::NAMESPACE,
            &test_key,
            &mut StateAccessMetric::new_read(), // We throw away the metric from this test query because it should almost always be cached and wasn't requested by the user
        );
        if state.encountered_pruning_error.is_some() {
            return Err(ApiStateAccessorError::HeightNotAccessible);
        }

        // Clear out any new values that were put in cache during initialization. Otherwise, we'd incorrectly estimate gas costs for
        // the first accesses to those values since they would be incorrectly shown as cached.
        state.clear_caches();
        Ok(state)
    }

    /// Clones the accessor for use in RPC contexts, dropping any local writes that were made to the accessor.
    pub fn clone_without_local_writes(&self) -> ApiStateAccessor<S> {
        ApiStateAccessor {
            witness: Default::default(),
            events: Vec::new(),
            gas_meter: self.gas_meter.clone(),
            local_kernel_writes: HashMap::new(),
            local_user_writes: HashMap::new(),
            local_accessory_writes: HashMap::new(),
            uncommitted_changes: self.uncommitted_changes.as_ref().map(|c| c.box_clone()),
            temp_cache: TempCache::new(),
            checkpoint_and_read_txn: self.checkpoint_and_read_txn.clone(),
            kernel: self.kernel.clone(),
            state_to_access: self.state_to_access,
            visible_slot_number: self.visible_slot_number,
            safe_true_slot_number_to_use: self.safe_true_slot_number_to_use,
            encountered_pruning_error: None,
            metrics: StateMetrics::default(),
        }
    }

    /// Returns a new accessor which accesses the rollup at the specified `height`.
    /// The gas price contained in the accessor is set to the base fee per gas at the specified height.
    pub fn get_archival_state(
        &self,
        height: RollupHeight,
    ) -> Result<ApiStateAccessor<S>, ApiStateAccessorError> {
        Self::build_archival_state(
            self.checkpoint_and_read_txn.state_checkpoint.clone(),
            self.uncommitted_changes.as_ref().map(|c| c.box_clone()),
            self.kernel.clone(),
            StateToAccess::RollupHeight(height),
        )
    }

    /// Returns an accessor suitable for `finalized`-tag RPC reads.
    ///
    /// The checkpoint carries explicit finalized policy because both preferred
    /// and standard sequencer modes can temporarily have the same finalized
    /// slot number while requiring different behavior:
    /// - preferred mode: finalized should follow the storage head;
    /// - standard mode: finalized should use the node-reported finalized slot.
    ///
    /// We therefore branch on policy, not on slot-number equality.
    pub fn build_finalized_state(&self) -> Result<ApiStateAccessor<S>, ApiStateAccessorError> {
        match self
            .checkpoint_and_read_txn
            .state_checkpoint
            .finalized_slot_policy()
        {
            FinalizedSlotPolicy::TrackStorageHead => Ok(self.clone_without_local_writes()),
            FinalizedSlotPolicy::UseExplicit(slot_number) => {
                Self::new_archival_with_true_slot_number(
                    self.checkpoint_and_read_txn.state_checkpoint.clone(),
                    self.kernel.clone(),
                    slot_number,
                )
            }
        }
    }

    /// Returns the latest finalized slot number available to this accessor.
    pub fn latest_finalized_slot_number(&self) -> SlotNumber {
        self.checkpoint_and_read_txn
            .state_checkpoint
            .latest_finalized_slot_number()
    }

    /// Get the true slot number being used for queries.
    #[cfg(feature = "test-utils")]
    pub fn true_slot_number_to_use(&self) -> SlotNumber {
        self.safe_true_slot_number_to_use.unwrap()
    }
}

impl<S: Spec> crate::state::accessors::StateMetricsProvider for ApiStateAccessor<S> {
    fn metrics(&mut self) -> &mut StateMetrics {
        &mut self.metrics
    }
}

impl<S: Spec> VersionReader for ApiStateAccessor<S> {
    fn current_visible_slot_number(&self) -> VisibleSlotNumber {
        self.visible_slot_number
            .expect("Visible slot number must be set during accessor initialization")
    }

    fn max_allowed_slot_number_to_access(&self) -> SlotNumber {
        self.current_visible_slot_number().as_true()
    }

    fn rollup_height_to_access(&self) -> RollupHeight {
        match self.state_to_access {
            StateToAccess::RollupHeight(rollup_height) => rollup_height,
            StateToAccess::TrueSlotNumber(_slot_number, Some(rollup_height)) => rollup_height,
            StateToAccess::TrueSlotNumber(slot_number, None) => {
                panic!("Rollup height not cached for slot number {slot_number}, but that slot exists in storage. This is a bug in ApiStateAccessor initialization. Please report it.");
            }
        }
    }
}

/// A wrapper around [`ApiStateAccessor`] that implements ProvableStateReader for both namespaces.
pub struct MeteredApiStateAccessor<S: Spec> {
    pub api_state_accessor: ApiStateAccessor<S>,
}

impl<S: Spec> GasMeter for MeteredApiStateAccessor<S> {
    type Spec = S;
    fn charge_gas(&mut self, amount: S::Gas) -> Result<(), GasMeteringError<S::Gas>> {
        self.api_state_accessor.gas_meter.charge_gas(amount)
    }
}

impl<S: Spec> VersionReader for MeteredApiStateAccessor<S> {
    fn max_allowed_slot_number_to_access(&self) -> SlotNumber {
        self.api_state_accessor.max_allowed_slot_number_to_access()
    }

    fn current_visible_slot_number(&self) -> VisibleSlotNumber {
        self.api_state_accessor.current_visible_slot_number()
    }

    fn rollup_height_to_access(&self) -> RollupHeight {
        self.api_state_accessor.rollup_height_to_access()
    }
}

impl<S: Spec> UniversalStateAccessor for MeteredApiStateAccessor<S> {
    fn get_size(
        &mut self,
        namespace: Namespace,
        key: &SlotKey,
        metric: &mut StateAccessMetric,
    ) -> Option<u32> {
        self.api_state_accessor.get_size(namespace, key, metric)
    }
    fn get_value(
        &mut self,
        namespace: Namespace,
        key: &SlotKey,
        metric: &mut StateAccessMetric,
    ) -> Option<SlotValue> {
        self.api_state_accessor.get_value(namespace, key, metric)
    }
    fn set_value(&mut self, namespace: Namespace, key: &SlotKey, value: SlotValue) {
        self.api_state_accessor.set_value(namespace, key, value);
    }
    fn delete_value(&mut self, namespace: Namespace, key: &SlotKey) {
        self.api_state_accessor.delete_value(namespace, key);
    }
}

impl<S: Spec> ProvableStateReader<namespaces::User> for MeteredApiStateAccessor<S> {}

impl<S: Spec> ProvableStateReader<namespaces::Kernel> for MeteredApiStateAccessor<S> {}

impl<S: Spec> GetGasPrice for MeteredApiStateAccessor<S> {
    type Spec = S;
    fn gas_price(&self) -> <S::Gas as Gas>::Price {
        self.api_state_accessor.gas_meter.gas_price
    }
}

impl<S: Spec> crate::state::accessors::StateMetricsProvider for MeteredApiStateAccessor<S> {
    fn metrics(&mut self) -> &mut StateMetrics {
        &mut self.api_state_accessor.metrics
    }
}
