[package]
name = "sov-aggregated-proof"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
hex = "0.4"
sha2 = "0.10.8"
anyhow = { version = "1.0.95" }
bincode = "1"
serde = { version = "1.0", default-features = false, features = ["derive"] }
serde_json = "1.0"
lazy_static = "1"

sp1-sdk = { version = "6.0.2", default-features = false, features = ["blocking"] }

sov-mock-da = { path = "../../adapters/mock-da" }
sov-state = { path = "../../module-system/sov-state" }
sov-rollup-interface = { path = "../../rollup-interface" }
sov-modules-api = { path = "../../module-system/sov-modules-api" }
sov-sp1-adapter = { path = "../../adapters/sp1" }
sov-mock-zkvm = { path = "../../adapters/mock-zkvm" }

[build-dependencies]
sp1-build = { version = "6.0.2", default-features = false }
anyhow = "1.0.95"
sov-zkvm-utils = { path = "../../utils/sov-zkvm-utils" }
