[package]
name = "sov-aggregated-proof-program"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
bincode = { workspace = true }
serde = { workspace = true }
demo-stf = { path = "../../../../examples/demo-rollup/stf", default-features = false }
sha2 = { workspace = true }
sp1-zkvm = { workspace = true }

sov-mock-da = { workspace = true }
sov-mock-zkvm = { workspace = true }
sov-modules-api = { workspace = true }
sov-rollup-interface = { workspace = true }
sov-sp1-adapter = { workspace = true }
