[build-system]
requires = ["maturin>=1.9,<2.0"]
build-backend = "maturin"

[project]
name = "sovereign_web3"
requires-python = ">=3.8"
classifiers = [
  "Programming Language :: Rust",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
dynamic = ["version"]
[tool.maturin]
features = ["pyo3/extension-module"]

[dependency-groups]
dev = ["cryptography>=46.0.3", "pytest>=8.3.5", "requests>=2.32.4"]

# https://github.com/PyO3/maturin/issues/2314
[tool.uv]
# Rebuild package when any rust files change
cache-keys = [
  { file = "pyproject.toml" },
  { file = "rust/Cargo.toml" },
  { file = "**/*.rs" },
]
# Uncomment to build rust code in development mode
# config-settings = { build-args = '--profile=dev' }
