use demo_stf::runtime::RuntimeSubcommand;
use sov_demo_rollup::CelestiaDemoRollup;
use sov_modules_api::cli::{FileNameArg, JsonStringArg};
use sov_modules_rollup_blueprint::WalletBlueprint;

include!("../../autogenerated.rs");

#[tokio::main]
async fn main() -> anyhow::Result<()> {
    CelestiaDemoRollup::run_wallet::<
        RuntimeSubcommand<FileNameArg, _>,
        RuntimeSubcommand<JsonStringArg, _>,
    >()
    .await
}
