[package]
name = "sov-db-types"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
homepage.workspace = true
publish.workspace = true
repository.workspace = true

[dependencies]
sov-rollup-interface = { workspace = true }
borsh = { workspace = true }
digest = { workspace = true }
rockbound = { workspace = true, optional = true }
arbitrary = { workspace = true, features = ["derive"], optional = true }
derivative = { workspace = true }
serde = { workspace = true }
hex = { workspace = true }
serde_with = { workspace = true }
proptest = { workspace = true, optional = true }
proptest-derive = { workspace = true, optional = true }

[lints]
workspace = true

[features]
default = []
native = ["dep:rockbound"]
arbitrary = [
    "dep:arbitrary",
	"dep:proptest",
	"dep:proptest-derive",
    "sov-rollup-interface/arbitrary",
]
