[package]
name = "da_client"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anchor-lang = "0.28.0"
anchor-client = "0.28.0"
solana-sdk = "=1.16.15"
borsh = "0.10.3"
bs58 = "0.5.0"
clap = { workspace = true }
blockroot = {path = "../solana_da_programs/programs/blockroot", features = ["no-entrypoint"]}
copy = {path = "../solana_da_programs/programs/copy", features = ["no-entrypoint"]}
solana-runtime = "=1.16.15"
solana-rpc-client = "=1.16.15"
anyhow = "1.0.75"
rand = "0.8.5"
lru = "0.12.0"
hex = "0.4.3"
blake3 = "1.3.3"
futures = "0.3.24"
env_logger = "0.10.0"
crossbeam = "0.8.2"
bincode = "1.3.3"
crossbeam-channel = "0.5.8"
backoff = { version = "0.4.0", features = ["tokio"] }
tokio = { version = "1.32.0", features = ["rt-multi-thread", "macros", "time"] }
log = { version = "0.4.14", features = ["std"] }
account_proof_geyser = { path = "../account_proof_geyser"}
yellowstone-grpc-proto = { git = "https://github.com/rpcpool/yellowstone-grpc.git", package = "yellowstone-grpc-proto", rev = "v1.9.0+solana.1.16.15" }
yellowstone-grpc-client = { git = "https://github.com/rpcpool/yellowstone-grpc.git", package = "yellowstone-grpc-client", rev = "v1.9.0+solana.1.16.15" }

[workspace]
