[package]
name = "py_sovereign_web3"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "sovereign_web3"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.25.0"
sovereign-web3 = { workspace = true, features = ["schema"] }
