[package]
name = "sov-eip712-auth"
description = "Sovereign authenticator for transactions signed using EIP712"
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

version = { workspace = true }
readme = "README.md"
publish = false

[lints]
workspace = true

[package.metadata.cargo-machete]
ignored = ["sov-universal-wallet"]

[dependencies]
sov-address = { workspace = true, features = ["evm"] } # to implement the compatibility marker on EvmCryptoSpec
sov-modules-api = { workspace = true }
sov-universal-wallet = { workspace = true, features = ["eip712"] } # enables Schema::eip712_signing_digest on the re-export used below
sov-state = { workspace = true }
anyhow = { workspace = true }
borsh = { workspace = true }
jsonrpsee = { workspace = true, features = ["jsonrpsee-types"] }
# For the stub RPC for chains not using EVM. Not needed for those using EVM,
# but in that case the dependency is almost certainly already present:
serde_json = { workspace = true } 

[dev-dependencies]
sov-eip712-auth = { path = ".", features = ["native"] }

[features]
native = [
	"sov-modules-api/native",
	"sov-state/native",
	"sov-address/native",
	"sov-eip712-auth/native"
]
