[package]
name = "sp1-microbenches"
version = "0.3.0"
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false

[lints]
workspace = true

[[bin]]
name = "sp1-microbenches"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
borsh = { workspace = true }
clap = { workspace = true }
serde = { workspace = true, features = ["derive"] }
sov-rollup-interface = { workspace = true, features = ["native"] }
sov-sp1-adapter = { workspace = true, features = ["native"] }
sp1-sdk = { workspace = true, features = ["blocking", "profiling"] }

[build-dependencies]
anyhow = { workspace = true }
sov-zkvm-utils = { workspace = true }
sp1-build = { workspace = true }
