pub mod genesis;
pub mod hooks;
pub mod query;
#[cfg(test)]
mod tests;
use sov_modules_api::Error;
use sov_modules_macros::ModuleInfo;
use sov_state::{StateValue, WorkingSet};

/// Initial configuration for the Sequencer module.
pub struct SequencerConfig<C: sov_modules_api::Context> {
    pub seq_rollup_address: C::Address,
    pub seq_da_address: Vec<u8>,
    pub coins_to_lock: bank::Coins<C>,
}

#[derive(ModuleInfo)]
pub struct Sequencer<C: sov_modules_api::Context> {
    /// The address of the Sequencer module
    /// Note: this is address is generated by the module framework and the corresponding private key is unknown.
    #[address]
    pub(crate) address: C::Address,

    /// Reference to the Bank module.
    #[module]
    pub(crate) bank: bank::Bank<C>,

    /// The sequencer address on the rollup.
    #[state]
    pub(crate) seq_rollup_address: StateValue<C::Address>,

    /// The sequencer address on the DA.
    #[state]
    pub(crate) seq_da_address: StateValue<Vec<u8>>,

    /// Coin's that will be slashed if the sequencer is malicious.
    /// The coins will be transferred from `self.seq_rollup_address` to `self.address`
    /// and locked forever.
    #[state]
    pub(crate) coins_to_lock: StateValue<bank::Coins<C>>,
}

impl<C: sov_modules_api::Context> sov_modules_api::Module for Sequencer<C> {
    type Context = C;

    #[cfg(feature = "native")]
    type QueryMessage = query::QueryMessage;

    type Config = SequencerConfig<C>;

    fn genesis(
        &self,
        config: &Self::Config,
        working_set: &mut WorkingSet<C::Storage>,
    ) -> Result<(), Error> {
        Ok(self.init_module(config, working_set)?)
    }

    #[cfg(feature = "native")]
    fn query(
        &self,
        msg: Self::QueryMessage,
        working_set: &mut WorkingSet<C::Storage>,
    ) -> sov_modules_api::QueryResponse {
        match msg {
            query::QueryMessage::GetSequencerAddressAndBalance => {
                let response =
                    serde_json::to_vec(&self.sequencer_address_and_balance(working_set)).unwrap();

                sov_modules_api::QueryResponse { response }
            }
        }
    }
}
