//! Build utilities for Sovereign SDK rollups.
//!
//! This crate provides tools for generating artifacts during the build process of Sovereign SDK rollups,
//! including runtime schema generation and JSON schema output.

use std::fs::File;
use std::io::Write;
use std::path::PathBuf;

use sov_modules_api::schemars::{schema_for, JsonSchema};
use sov_modules_api::transaction::TransactionCallable;
use sov_modules_api::{DispatchCall, Spec};

/// Builder for configuring build options.
///
/// Provides a fluent API for setting up build configuration with sensible defaults.
pub struct OptionsBuilder {
    out_dir: PathBuf,
    rust_autogenerated_path: Option<PathBuf>,
    rollup_schema: bool,
    json_schema: bool,
    set_git_hash: bool,
}

impl Default for OptionsBuilder {
    fn default() -> Self {
        Self {
            out_dir: PathBuf::from(".artifacts"),
            rust_autogenerated_path: None,
            rollup_schema: false,
            json_schema: true,
            set_git_hash: false,
        }
    }
}

impl OptionsBuilder {
    /// Sets the output directory for generated artifacts.
    ///
    /// Default: `.artifacts`
    pub fn out_dir<P: Into<PathBuf>>(mut self, path: P) -> Self {
        self.out_dir = path.into();
        self
    }

    /// Sets a custom path for the autogenerated Rust constants file.
    ///
    /// If not set, defaults to `{out_dir}/autogenerated.rs`.
    pub fn rust_autogenerated_path<P: Into<PathBuf>>(mut self, path: P) -> Self {
        self.rust_autogenerated_path = Some(path.into());
        self
    }

    /// Controls whether to generate rollup schema JSON file.
    ///
    /// Default: `true`
    pub fn rollup_schema(mut self, enabled: bool) -> Self {
        self.rollup_schema = enabled;
        self
    }

    /// Controls whether to generate JSON schema file.
    ///
    /// Default: `true`
    pub fn json_schema(mut self, enabled: bool) -> Self {
        self.json_schema = enabled;
        self
    }

    /// Controls whether to set the git commit hash as a cargo environment variable `GIT_COMMIT_HASH`.
    /// Requires `git` cli tool to be available in the build environment.
    ///
    /// Default: `false`
    pub fn set_git_hash(mut self, enabled: bool) -> Self {
        self.set_git_hash = enabled;
        self
    }

    /// Builds the final `Options` configuration.
    pub fn build(self) -> Options {
        Options {
            out_dir: self.out_dir,
            rust_autogenerated_path: self.rust_autogenerated_path,
            rollup_schema: self.rollup_schema,
            json_schema: self.json_schema,
            set_git_hash: self.set_git_hash,
        }
    }
}

/// Configuration options for the build process.
///
/// Contains all settings for controlling artifact generation during the build.
pub struct Options {
    pub out_dir: PathBuf,
    pub rust_autogenerated_path: Option<PathBuf>,
    pub rollup_schema: bool,
    pub json_schema: bool,
    pub set_git_hash: bool,
}

impl Options {
    /// Creates a new `OptionsBuilder` with default settings.
    pub fn builder() -> OptionsBuilder {
        Default::default()
    }

    /// Applies the build configuration and generates all enabled artifacts.
    ///
    /// # Example
    ///
    /// ```ignore
    /// use sov_build::{Options, BuildSpec};
    /// use your_rollup::{YourRuntime, YourAddress};
    ///
    /// type S = BuildSpec<YourAddress>;
    ///
    /// fn main() -> anyhow::Result<()> {
    ///     let options = Options::builder()
    ///         .out_dir("build/artifacts")
    ///         .rollup_schema(true)
    ///         .json_schema(false)
    ///         .build()
    ///         .apply::<S, YourRuntime<S>>()
    /// }
    /// ```
    pub fn apply<S, D>(&self) -> anyhow::Result<()>
    where
        S: Spec,
        D: DispatchCall + TransactionCallable + 'static,
        D::Decodable: JsonSchema,
    {
        std::fs::create_dir_all(&self.out_dir)?;
        self.output_rust_constants::<S, D>()?;

        if self.set_git_hash {
            self.set_git_head_env()?;
        }

        if self.rollup_schema {
            self.output_rollup_schema::<S, D>()?;
        }

        if self.json_schema {
            self.output_json_schema::<D>()?;
        }

        Ok(())
    }

    /// Applies the default build configuration options and generates build time artifacts.
    ///
    /// # Example
    ///
    /// ```ignore
    /// use your_rollup::{YourRuntime, YourAddress};
    ///
    /// fn main() -> anyhow::Result<()> {
    ///     sov_build::Options::apply_defaults::<S, YourRuntime<S>>()
    /// }
    /// ```
    pub fn apply_defaults<S, D>() -> anyhow::Result<()>
    where
        S: Spec,
        D: DispatchCall + TransactionCallable + 'static,
        D::Decodable: JsonSchema,
    {
        Self::builder().build().apply::<S, D>()
    }

    fn output_rust_constants<S, D>(&self) -> anyhow::Result<()>
    where
        S: Spec,
        D: DispatchCall + TransactionCallable + 'static,
    {
        let out_path = self
            .rust_autogenerated_path
            .clone()
            .unwrap_or_else(|| self.out_dir.join("autogenerated.rs"));
        let schema =
            sov_modules_api::runtime::get_runtime_schema::<S, D>().expect("Failed to get schema");
        let schema_json = serde_json::to_string_pretty(&schema)?;
        let mut file = File::create(out_path)?;
        let chain_hash = schema.cached_chain_hash().unwrap();

        write!(
            &mut file,
            "pub const CHAIN_HASH: [u8; 32] = {chain_hash:?};\n\n"
        )?;
        write!(
            &mut file,
            "#[allow(dead_code)]\npub const SCHEMA_JSON: &str = r#\"{schema_json}\"#;\n"
        )?;

        Ok(())
    }

    fn output_rollup_schema<S, D>(&self) -> anyhow::Result<()>
    where
        S: Spec,
        D: DispatchCall + TransactionCallable + 'static,
    {
        let out_path = self.out_dir.join("rollup-schema.json");
        let schema =
            sov_modules_api::runtime::get_runtime_schema::<S, D>().expect("Failed to get schema");
        let json = serde_json::to_string_pretty(&schema)?;
        let mut file = File::create(out_path)?;

        file.write_all(json.as_bytes())?;
        file.write_all(b"\n")?;

        Ok(())
    }

    fn output_json_schema<D>(&self) -> anyhow::Result<()>
    where
        D: DispatchCall + TransactionCallable + 'static,
        D::Decodable: JsonSchema,
    {
        let out_path = self.out_dir.join("json-schema.json");
        let schema = schema_for!(D::Decodable);
        let json = serde_json::to_string_pretty(&schema)?;
        let mut file = File::create(out_path)?;

        file.write_all(json.as_bytes())?;
        file.write_all(b"\n")?;

        Ok(())
    }

    fn set_git_head_env(&self) -> anyhow::Result<()> {
        let output = std::process::Command::new("git")
            .args(["rev-parse", "HEAD"])
            .output()?;

        if output.status.success() {
            let hash = String::from_utf8_lossy(&output.stdout).trim().to_string();
            println!("cargo:rustc-env=GIT_COMMIT_HASH={hash}");
            Ok(())
        } else {
            anyhow::bail!(
                "Failed to set commit hash, git command exited with code {:?}",
                output.status.code()
            )
        }
    }
}
