[package]
name = "sov-eth-client"
description = "Client for the Sovereign SDK Ethereum APIs"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
publish = false

[dependencies]
anyhow = { workspace = true }
alloy = { workspace = true, features = ["reqwest"] }
alloy-consensus = { workspace = true }
alloy-eips = { workspace = true }
alloy-primitives = { workspace = true }
alloy-rpc-types  = { workspace = true }
alloy-provider = { workspace = true }
alloy-pubsub = { workspace = true }
alloy-signer = { workspace = true }
reqwest = { workspace = true }
async-trait = { workspace = true }
derive_more = { workspace = true }
futures = { workspace = true }
jsonrpsee = { workspace = true, features = ["ws-client"] }
serde = { workspace = true }
sov-cli = { workspace = true }
sov-modules-api = { workspace = true }
sov-evm-test-utils = { workspace = true }
sov-rpc-eth-types = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
