services:
  validator:
    image: ghcr.io/sovereign-labs/celestia-validator-devnet:v7.0.2-mocha
    hostname: validator
    environment:
      NO_COLOR: 1
    # uncomment to provide amount of sequencers to provision (default: 5)
    # command: [ "/opt/entrypoint.sh", "2" ]
    ports:
      - "127.0.0.1:9090:9090"
    volumes:
      - type: bind
        source: ./credentials
        target: /credentials
      - genesis:/genesis

  sequencer-0:
    image: ghcr.io/sovereign-labs/celestia-bridge-devnet:v0.29.1-mocha
    hostname: sequencer-0
    depends_on:
      - validator
    # uncomment to provide the id of the sequencer (default: 0)
    # command: ["/opt/entrypoint.sh", "0"]
    environment:
      NO_COLOR: 1
    ports:
      - "127.0.0.1:${CELESTIA_PORT:-26658}:26658"
    volumes:
      - type: bind
        source: ./credentials
        target: /credentials
        consistency: consistent
      - genesis:/genesis

volumes:
  # a temporary fs where the genesis hash is announced
  genesis:
    driver_opts:
      type: tmpfs
      device: tmpfs
