[package]
name = "sov-prover-incentives"
description = "A Sovereign SDK module for incentivizing provers"
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }
readme = "README.md"
resolver = "2"

[dev-dependencies]
sov-rollup-interface = { path = "../../../rollup-interface", version = "0.1", features = ["mocks"] }
sov-modules-api = { path = "../../sov-modules-api", version = "0.1", features = ["native"] }
tempfile = { workspace = true }
sov-prover-incentives = { version = "*", features = ["native"], path = "." }

[dependencies]
anyhow = { workspace = true }
borsh = { workspace = true, features = ["rc"] }
bincode = { workspace = true }
schemars = { workspace = true, optional = true }
serde = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }

sov-bank = { path = "../sov-bank", version = "0.1" }
sov-modules-api = { path = "../../sov-modules-api", version = "0.1" }
sov-state = { path = "../../sov-state", version = "0.1" }


[features]
default = []
native = ["serde", "serde_json", "schemars", "sov-state/native", "sov-modules-api/native"]