[package]
name = "sov-demo-prover-guest-celestia-sp1"
version = "0.3.0"
license = "MIT OR Apache-2.0"
edition = "2021"
resolver = "2"

[workspace]

[dependencies]
sp1-zkvm = { version = "6.0.2" }
demo-stf = { path = "../../../stf" }
sov-sp1-adapter = { path = "../../../../../crates/adapters/sp1" }
sov-celestia-adapter = { path = "../../../../../crates/adapters/celestia" }
sov-mock-zkvm = { path = "../../../../../crates/adapters/mock-zkvm" }
sov-rollup-interface = { path = "../../../../../crates/rollup-interface" }
sov-modules-api = { path = "../../../../../crates/module-system/sov-modules-api" }
sov-address = { path = "../../../../../crates/module-system/sov-address" }
sov-state = { path = "../../../../../crates/module-system/sov-state" }
sov-modules-stf-blueprint = { path = "../../../../../crates/module-system/sov-modules-stf-blueprint" }
sov-kernels = { path = "../../../../../crates/module-system/sov-kernels" }
sov-metrics = { path = "../../../../../crates/full-node/sov-metrics", optional = true, features = [
    "sp1",
] }

[profile.dev]
opt-level = 3

[profile.dev.build-override]
opt-level = 3

[profile.release]
debug = 1
lto = true

[profile.release.build-override]
opt-level = 3

[features]
bench = [
    "sov-modules-api/bench",
    "sov-state/bench",
    "sov-modules-stf-blueprint/bench",
    "sov-celestia-adapter/bench",
]
