[package]
name = "rest-api-load-testing"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
publish = false


[lints]
workspace = true

[dependencies]
clap = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "time", "net", "signal"] }
reqwest = { workspace = true }
anyhow = { workspace = true }
futures = { workspace = true }
tokio-tungstenite = { workspace = true, features = ["connect", "rustls-tls-native-roots"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
base64 = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
borsh = { workspace = true }
demo-stf = { workspace = true, features = ["native"] }
sov-bank = { workspace = true, features = ["native"] }
sov-cli = { workspace = true }
sov-mock-da = { workspace = true }
sov-mock-zkvm = { workspace = true }
sov-modules-api = { workspace = true }
sov-node-client = { workspace = true }
sov-rollup-interface = { workspace = true }
sov-state = { workspace = true }
sov-test-utils = { workspace = true }
