//! Tests for shutdown/restart cases.
use std::collections::HashSet;
use std::env;
use std::str::FromStr;
use std::sync::Arc;
use std::time::Duration;

use anyhow::{bail, Context};
use base64::prelude::BASE64_STANDARD;
use base64::Engine;
use demo_stf::runtime::{Runtime as DemoRuntime, RuntimeCall};
use demo_stf_json_client::types::RuntimeAnyJsonValue;
use futures::StreamExt;
use sov_api_spec::types::{SyncStatus, TxStatus};
use sov_demo_rollup::{mock_da_risc0_host_args, MockDemoRollup};
use sov_modules_api::execution_mode::Native;
use sov_modules_api::{OperatingMode, RawTx, Runtime, TxHash};
use sov_modules_rollup_blueprint::logging::default_rust_log_value;
use sov_risc0_adapter::crypto::private_key::Risc0PrivateKey;
use sov_stf_runner::processes::RollupProverConfig;
use sov_test_utils::logging::LogCollector;
use sov_test_utils::test_rollup::{read_private_key, RollupBuilder, TestRollup};
use sov_test_utils::{default_test_signed_transaction, TEST_DEFAULT_MOCK_DA_PERIODIC_PRODUCING};
use tempfile::TempDir;
use tracing::Level;
use tracing_subscriber::prelude::*;
use tracing_subscriber::{registry, EnvFilter, Layer};

use crate::test_helpers::{test_genesis_source, DemoRollupSpec};

const ROLLUP_START_TIMEOUT: std::time::Duration = std::time::Duration::from_secs(10);
const ROLLUP_SYNC_TIMEOUT: std::time::Duration = std::time::Duration::from_secs(60);
const TX_PROCESSING_TIMEOUT: std::time::Duration = std::time::Duration::from_secs(10);
const ROLLUP_SHUTDOWN_TIMEOUT: std::time::Duration = std::time::Duration::from_secs(5);

fn initialize_logging_for_resync(collector: LogCollector, with_stdout: bool) {
    let subscriber = registry().with(collector);
    let prev_hook = std::panic::take_hook();
    std::panic::set_hook(Box::new(move |panic_info| {
        tracing_panic::panic_hook(panic_info);
        prev_hook(panic_info);
    }));
    if with_stdout {
        let env_filter =
            env::var("RUST_LOG").unwrap_or_else(|_| default_rust_log_value().to_string());

        let get_env_filter = || EnvFilter::from_str(&env_filter).unwrap();
        let layer = tracing_subscriber::fmt::layer()
            .with_filter(get_env_filter())
            .boxed();

        subscriber.with(layer).init();
    } else {
        subscriber.init();
    }
}

// Must be pre-sorted
const VAL_AT_SLOT: [(u64, u64); 5] = [(10, 10), (20, 15), (40, 20), (80, 25), (100, 30)];
const CHECK_TRANSACTION_VALUE: u64 = 13;

const DA_SLOTS_TO_GENERATE: u64 = 100;
const FINALIZATION_SLOTS: u32 = 5;

fn tx_set_value_for_check(key: Risc0PrivateKey, value: u64, nonce: u64) -> RawTx {
    let msg: RuntimeCall<DemoRollupSpec> =
        RuntimeCall::SyntheticLoad(sov_synthetic_load::CallMessage::ReadAndSetHeavyState {
            number_of_new_values: value,
            max_heavy_state_size: value,
            salt: 10,
        });
    let tx = default_test_signed_transaction::<DemoRuntime<DemoRollupSpec>, DemoRollupSpec>(
        &key,
        &msg,
        nonce,
        &<DemoRuntime<DemoRollupSpec> as Runtime<DemoRollupSpec>>::CHAIN_HASH,
    );
    RawTx::new(borsh::to_vec(&tx).unwrap())
}

async fn check_value(client: &demo_stf_json_client::Client, expected: u64) {
    let response = client
        .synthetic_load_heavy_state_get_state_value(None, None)
        .await
        .unwrap()
        .into_inner();

    match &*response {
        RuntimeAnyJsonValue::Object(inner) => {
            let state_value = inner.get("value").unwrap();
            let heavy_vec = state_value.as_array().unwrap();
            assert_eq!(heavy_vec.len(), expected as usize);
        }
        _ => panic!("Getting SyntheticLoad state value returned unexpected JSON shape."),
    }
}

/// This "test" generates a mock_da.sqlite artifact that can then be used for rescyncing tests.
/// It is marked as a test to allow a convenient way to run as a self-contained binary, using
/// ```
/// SKIP_GUEST_BUILD=1 cargo nextest run test_generate_mockda_dataset_for_resync --run-ignored all --no-capture
/// ```
/// Thus the artifact used to test resyncing can easily be conveniently and reproducibly
/// regenerated whenever needed.
///
/// It is NOT, however, meant to be ran as part of normal testing or CI. The generated artifact is
/// committed to git and is meant to be reused long-term, only regenerated by manual invokation
/// when it needs to be changed for whatever reason.
#[tokio::test(flavor = "multi_thread")]
#[ignore]
async fn test_generate_mockda_dataset_for_resync() -> anyhow::Result<()> {
    let rollup_storage_path = Arc::new(TempDir::new_in("tests/resync/data/")?);

    let test_rollup = tokio::time::timeout(
        ROLLUP_START_TIMEOUT,
        RollupBuilder::<MockDemoRollup<Native>>::new_with_storage_path(
            test_genesis_source(OperatingMode::Zk),
            TEST_DEFAULT_MOCK_DA_PERIODIC_PRODUCING,
            FINALIZATION_SLOTS,
            rollup_storage_path.clone(),
        )
        .with_zkvm_host_args(mock_da_risc0_host_args())
        .set_config(|c| {
            c.rollup_prover_config = Some(RollupProverConfig::Skip);
            c.aggregated_proof_block_jump = 10;
            c.max_concurrent_blobs = 92;
        })
        .start(),
    )
    .await
    .context("Starting rollup failed")??;

    let tx_signer_key =
        read_private_key::<DemoRollupSpec>("tx_signer_private_key.json").private_key;

    let mut slot_subscription = test_rollup.client.client.subscribe_slots().await?;

    let mut known_values_to_set = VAL_AT_SLOT.iter().peekable();
    loop {
        let current_slot_number = slot_subscription
            .next()
            .await
            .transpose()?
            .map(|s| s.number)
            .unwrap_or_default();
        if let Some((height, value)) = known_values_to_set.peek() {
            if current_slot_number == *height {
                known_values_to_set.next();
                let tx = tx_set_value_for_check(tx_signer_key.clone(), *value, current_slot_number);
                test_rollup
                    .api_client
                    .accept_tx(&sov_api_spec::types::AcceptTxBody {
                        body: BASE64_STANDARD.encode(&tx),
                    })
                    .await
                    .unwrap();
                test_rollup.force_close_batch().await.unwrap();
            }
        }
        if current_slot_number >= DA_SLOTS_TO_GENERATE + FINALIZATION_SLOTS as u64 {
            break;
        }
    }

    let finalized_slot = test_rollup
        .client
        .client
        .get_finalized_slot(Some(sov_api_spec::types::GetFinalizedSlotChildren::_0))
        .await?;
    tracing::debug!("Finalized slot response: {finalized_slot:?}");

    let TestRollup {
        shutdown_sender,
        rollup_task,
        da_service,
        ..
    } = test_rollup;

    drop(da_service);
    tracing::info!("Triggering shutdown....");
    shutdown_sender.send(())?;
    tokio::time::timeout(ROLLUP_SHUTDOWN_TIMEOUT, rollup_task)
        .await
        .context("Joining rollup task failed")???;

    // Sleep to let the rollup clean up and possibly close the sqlite DB more gracefully
    tokio::time::sleep(Duration::from_millis(1000)).await;

    std::fs::copy(
        rollup_storage_path.path().join("mock_da.sqlite"),
        "tests/resync/data/mock_da.sqlite",
    )?;

    // Sometimes this test still leaves the sqlite WAL unflushed. So we copy it too.
    // It has to be manually flushed afterwards, e.g. simply opening the db with sqlitebrowser is
    // enough.
    let wal_path = rollup_storage_path.path().join("mock_da.sqlite-wal");
    if wal_path.exists() {
        std::fs::copy(wal_path, "tests/resync/data/mock_da.sqlite-wal")?;
    }
    let shm_path = rollup_storage_path.path().join("mock_da.sqlite-shm");
    if shm_path.exists() {
        std::fs::copy(shm_path, "tests/resync/data/mock_da.sqlite-shm")?;
    }
    Ok(())
}

/// The actual resync test, using a pre-generated mock_da database.
///
/// Important Note: This test may fail if you've made any changes that could modify the chain hash,
/// including adding/removing call message variants to any module in demo-rollup. Remove
/// `test/resync/data` and run `test_generate_mockda_dataset_for_resync` to update the data.
#[tokio::test(flavor = "multi_thread")]
async fn test_rollup_resync() -> anyhow::Result<()> {
    // Deferred slots are set low in tests. If resyncing takes too long, the sequencer can
    // legitimately fall behind. We don't care about testing that here, so bump the count to give
    // the sequencer time to resync safely.
    std::env::set_var("SOV_TEST_CONST_OVERRIDE_DEFERRED_SLOTS_COUNT", "400");

    let collector = LogCollector::new(Level::WARN);
    initialize_logging_for_resync(collector.clone(), false); // Set to true to see logs

    let rollup_storage_path = Arc::new(TempDir::new_in("tests/resync/data/")?);

    // First, simple test: resync from the existing DA storage
    std::fs::copy(
        "tests/resync/data/mock_da.sqlite",
        rollup_storage_path.path().join("mock_da.sqlite"),
    )?;
    sync_rollup_with_path(rollup_storage_path.clone(), 10_000).await?;

    // Next, delete everything except the preferred sequencer DB. Resync again to verify that this
    // doesn't interfere
    for path in ["state", "accessory", "ledger", "blob_sender"] {
        std::fs::remove_dir_all(rollup_storage_path.path().join(path))?;
    }
    // sanity check
    let mut remaining_paths: HashSet<_> = std::fs::read_dir(rollup_storage_path.path())?
        .filter_map(Result::ok)
        .map(|entry| entry.file_name().to_string_lossy().into_owned())
        .collect();
    assert!(
        remaining_paths.remove("mock_da.sqlite"),
        "mock_da.sqlite must be present"
    );
    assert!(
        remaining_paths.remove("preferred_sequencer"),
        "preferred_sequencer must be present"
    );

    // Sometimes the rollup leaves behind the sqlite WAL, check for this as part of the sanity check
    let optional_files: HashSet<&str> = ["mock_da.sqlite-wal", "mock_da.sqlite-shm"]
        .into_iter()
        .collect();
    let remaining_str_paths: HashSet<&str> = remaining_paths.iter().map(|s| s.as_str()).collect();
    assert!(
        remaining_str_paths.is_subset(&optional_files),
        "Unexpected files found: {:?}",
        remaining_str_paths
            .difference(&optional_files)
            .collect::<Vec<_>>()
    );

    sync_rollup_with_path(rollup_storage_path, 20_000).await?;

    // Check the rollup did not emit any warnings or errors at any point during the tests
    let known_acceptable_logs = [
        // TODO - investigate slow postgres queries (optimisation item in
        // https://github.com/Sovereign-Labs/sovereign-sdk-wip/issues/2800)
        (Level::WARN, "slow statement: execution time exceeded alert threshold".to_string()),
        // TODO - investigate: https://github.com/Sovereign-Labs/sovereign-sdk-wip/issues/2978
        (Level::WARN, "Received error updating target height, stopping background task".to_string()),
        // This is expected for the second resync: since we have batches in the sequencer DB, we
        // are indeed causing a delay for users
        (Level::WARN, "The sequencer must pause because the node has lagged behind the DA blockchain. This might lead to a brief downtime for users.".to_string()),
        // This is due to finalized but recent enough proof blobs not being pruned for a while (see
        // the TODO inside `prune_sequencer_db` in the preferred sequencer db mod.rs). This
        // causes the sequencer to resubmit proof blobs for earlier slots, which are no longer
        // valid. This is likely related to https://github.com/Sovereign-Labs/sovereign-sdk-wip/issues/1878
        // (sending already-submitted proofs at a later height).
        (Level::ERROR, "Invalid proof outcome".to_string()),
        // On resync, we expect to see this log because we re-process old state in the node and then try 
        // to prune the equivalent state from the sequencer. It doesnt' exist and that's fine.
        (Level::WARN, "Skipping pruning of sequence number because it's already been pruned".to_string()),
        // This shows up occasionally, but especially often on hetzner. There may be some timing
        // oddity that might be worth investigating.
        (Level::WARN, "State Transition Info is not consumed fast enough, cannot prune older entries. Please check that consumer works.".to_string())
    ];

    let mut recorded_errors_warnings =
        HashSet::<(Level, String)>::from_iter(collector.records().iter().cloned());
    recorded_errors_warnings.retain(|e| !known_acceptable_logs.contains(e));
    // We could've checked `.is_empty`, but in case of failure, we will see errors immediately.
    assert_eq!(HashSet::<(Level, String)>::new(), recorded_errors_warnings);
    Ok(())
}

// Does a full resync test using a given data directory.
// 1. Starts a rollup in the given directory
// 2. Verifies the state matches the expected state at intermediate points while resyncing
// 3. Verifies the rollup eventually catches up to the DA and finishes syncing
// 4. Sends a transaction, verifies that the rollup accepts it, applies it, and that state is
//    visibly affected (to ensure the rollup functions correctly)
// 5. Shuts down the rollup
async fn sync_rollup_with_path(
    rollup_storage_path: Arc<TempDir>,
    nonce_to_use: u64,
) -> anyhow::Result<()> {
    let test_rollup = tokio::time::timeout(
        ROLLUP_START_TIMEOUT,
        RollupBuilder::<MockDemoRollup<Native>>::new_with_storage_path(
            test_genesis_source(OperatingMode::Zk),
            TEST_DEFAULT_MOCK_DA_PERIODIC_PRODUCING,
            5,
            rollup_storage_path.clone(),
        )
        .with_zkvm_host_args(mock_da_risc0_host_args())
        .set_config(|c| {
            c.rollup_prover_config = Some(RollupProverConfig::Skip);
            c.aggregated_proof_block_jump = 10;
            c.max_concurrent_blobs = 92;
        })
        .start(),
    )
    .await
    .context("Starting rollup failed")??;

    let mut slot_subscription = test_rollup.api_client.subscribe_slots().await?;
    let demo_client = demo_stf_json_client::Client::new(&test_rollup.client.base_url);

    // Validate state at each sync height
    let mut known_values_that_have_been_set = VAL_AT_SLOT.iter().peekable();

    // To make this perfectly flake-free, the `generate_dataset` test should save the exact height
    // each transaction got included in the DA as an auxilliary artifact. However just waiting a
    // few blocks is reliable enough for now.
    const INCLUSION_DELAY_SLACK: u64 = 4;
    loop {
        let current_slot_number = slot_subscription
            .next()
            .await
            .transpose()?
            .map(|s| s.number)
            .unwrap_or_default();
        if let Some((height, value)) = known_values_that_have_been_set.peek() {
            if current_slot_number == *height + INCLUSION_DELAY_SLACK {
                known_values_that_have_been_set.next();
                check_value(&demo_client, *value).await;
            }
        }
        if current_slot_number >= DA_SLOTS_TO_GENERATE + FINALIZATION_SLOTS as u64 {
            break;
        }
    }

    tokio::time::timeout(ROLLUP_SYNC_TIMEOUT, async {
        while let SyncStatus::Syncing { .. } =
            *test_rollup.api_client.get_sync_status().await.unwrap()
        {
            tokio::time::sleep(Duration::from_secs(2)).await;
        }
    })
    .await
    .context("Fully resyncing to the DA tip timed out")?;
    // We need to sleep because the sync status is based on the DA service updated by the node,
    // but the sequencer needs to run update_state() first.
    tokio::time::sleep(Duration::from_millis(1000)).await;
    tracing::info!("Synced!");

    // Ensure the rollup can still accept transactions
    let tx_signer_key =
        read_private_key::<DemoRollupSpec>("tx_signer_private_key.json").private_key;
    let tx = tx_set_value_for_check(tx_signer_key.clone(), CHECK_TRANSACTION_VALUE, nonce_to_use);
    let accept_tx = test_rollup
        .api_client
        .accept_tx(&sov_api_spec::types::AcceptTxBody {
            body: BASE64_STANDARD.encode(&tx),
        })
        .await
        .unwrap();
    let tx_hash = accept_tx.id.clone();
    let hex_tx_hash = TxHash::from_str(tx_hash.as_str()).unwrap(); // I wonder if there's a better way
    let mut tx_subscription = test_rollup
        .api_client
        .subscribe_to_tx_status_updates(hex_tx_hash)
        .await
        .unwrap();
    tokio::time::timeout(TX_PROCESSING_TIMEOUT, async {
        loop {
            let status = tx_subscription
                .next()
                .await
                .transpose()?
                .map(|info| info.status);
            if let Some(TxStatus::Processed) = status {
                break Ok(());
            } else if status.is_none() {
                bail!(
                    "Transaction status updates terminated without transaction getting processed"
                );
            }
        }
    })
    .await
    .context("Finalizing the transaction failed")??;
    check_value(&demo_client, CHECK_TRANSACTION_VALUE).await;

    let TestRollup {
        shutdown_sender,
        rollup_task,
        da_service,
        ..
    } = test_rollup;

    drop(da_service);
    tracing::info!("Triggering shutdown....");
    shutdown_sender.send(())?;
    tokio::time::timeout(ROLLUP_SHUTDOWN_TIMEOUT, rollup_task)
        .await
        .context("Joining rollup task failed")???;
    Ok(())
}
