[package]
name = "proxy-utils"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
sqlx = { version = "0.8", features = ["runtime-tokio", "postgres"] }
tokio = { workspace = true }
tracing = { workspace = true }
