//! This module implements `Runtime` trait and ensures that it uses correct `CHAIN_HASH`.

#[cfg(feature = "native")]
use sov_evm::execution_config::EvmExecutionConfig;
use sov_hyperlane_integration::HyperlaneAddress;
use sov_solana_offchain_auth::SolanaOffchainAuthenticatorTrait;
#[cfg(feature = "native")]
use sov_state::pinned_cache::PinnedCache;
#[cfg(feature = "native")]
use std::sync::Arc;

use sov_address::{EthereumAddress, FromVmAddress};
#[cfg(feature = "native")]
pub use sov_attester_incentives::BondingProofServiceImpl;
use sov_capabilities::StandardProvenRollupCapabilities as StandardCapabilities;
use sov_evm::EthereumAuthenticator;
use sov_kernels::soft_confirmations::SoftConfirmationsKernel;
#[cfg(feature = "native")]
use sov_modules_api::capabilities::KernelWithSlotMapping;
use sov_modules_api::capabilities::{Guard, HasCapabilities, HasKernel, TransactionAuthenticator};
use sov_modules_api::Base58Address;
use sov_modules_api::{RawTx, Spec};

pub use demo_stf_declaration::GenesisConfig;
use demo_stf_declaration::Runtime as RuntimeInner;
pub use demo_stf_declaration::RuntimeCall;
#[cfg(feature = "native")]
pub use demo_stf_declaration::RuntimeSubcommand;

use crate::authentication::{
    EvmAndSolanaOffchainAuthenticator, EvmAndSolanaOffchainAuthenticatorInput,
};
#[cfg(feature = "native")]
use crate::genesis_config::GenesisPaths;

// CHAIN_HASH and Schema are generated during build time.
// This allows make sure that Runtime can be authenticated in ZKVM guest.
#[allow(missing_docs)]
pub mod __generated {
    include!("../.artifacts/autogenerated.rs");
}

/// The chain hash constant, re-exported for convenience.
pub use __generated::CHAIN_HASH;

/// The `demo-stf runtime`.
#[derive(Default, Clone)]
pub struct Runtime<S: Spec>(pub(crate) RuntimeInner<S>)
where
    S::Address: FromVmAddress<EthereumAddress> + FromVmAddress<Base58Address> + HyperlaneAddress;

impl<S: Spec> std::ops::Deref for Runtime<S>
where
    S::Address: FromVmAddress<EthereumAddress> + FromVmAddress<Base58Address> + HyperlaneAddress,
{
    type Target = RuntimeInner<S>;
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}

impl<S: Spec> std::ops::DerefMut for Runtime<S>
where
    S::Address: FromVmAddress<EthereumAddress> + FromVmAddress<Base58Address> + HyperlaneAddress,
{
    fn deref_mut(&mut self) -> &mut Self::Target {
        &mut self.0
    }
}

impl<S> sov_modules_stf_blueprint::Runtime<S> for Runtime<S>
where
    S: Spec,
    S::Address: FromVmAddress<EthereumAddress> + FromVmAddress<Base58Address> + HyperlaneAddress,
{
    const CHAIN_HASH: [u8; 32] = __generated::CHAIN_HASH;

    type GenesisConfig = GenesisConfig<S>;

    #[cfg(feature = "native")]
    type GenesisInput = GenesisPaths;

    #[cfg(feature = "native")]
    type ModuleExecutionConfig = EvmExecutionConfig;

    type Auth = EvmAndSolanaOffchainAuthenticator<S, Self>;

    #[cfg(feature = "native")]
    fn endpoints(
        api_state: sov_modules_api::rest::ApiState<S>,
    ) -> ::sov_modules_api::NodeEndpoints {
        use ::sov_modules_api::rest::HasRestApi;
        use ::sov_rollup_apis::endpoints::dedup::{DeDupEndpoint, SovereignDeDupEndpoint};
        use ::sov_rollup_apis::endpoints::schema::{SchemaEndpoint, StandardSchemaEndpoint};

        let axum_router = Self::default().0.rest_api(api_state.clone());
        // Provide an endpoint to return dedup information associated with addresses.
        // Since our runtime is using the uniqueness module we can use the provided `NonceDeDupEndpoint` implementation.
        let dedup_endpoint = SovereignDeDupEndpoint::new(api_state.clone());
        let axum_router = axum_router.merge(dedup_endpoint.axum_router());

        // StandardSchemaEndpoint resolves chain hash based on current height.
        // This ensures wallets get the correct chain hash during chain hash transitions.
        let schema_endpoint = StandardSchemaEndpoint::<S>::new(
            &serde_json::from_str(__generated::SCHEMA_JSON)
                .expect("Failed to deserialize schema json"),
            Self::CHAIN_HASH.into(),
            api_state.checkpoint_receiver(),
        )
        .expect("Failed to initialize StandardSchemaEndpoint");
        let axum_router = axum_router.merge(schema_endpoint.axum_router());
        let axum_router = axum_router.merge(sov_rollup_apis::endpoints::constants::axum_router());

        ::sov_modules_api::NodeEndpoints {
            axum_router,
            jsonrpsee_module: demo_stf_declaration::get_rpc_methods::<S>(api_state),
            background_handles: Vec::new(),
        }
    }

    #[cfg(feature = "native")]
    fn resolve_address<ST: sov_modules_api::StateReader<sov_modules_api::User>>(
        &self,
        default_address: &S::Address,
        credential_id: &sov_modules_api::CredentialId,
        state: &mut ST,
    ) -> Result<S::Address, ST::Error> {
        self.0
            .accounts
            .resolve_sender_address_read_only(default_address, credential_id, state)
    }

    #[cfg(feature = "native")]
    fn genesis_config(input: &Self::GenesisInput) -> anyhow::Result<Self::GenesisConfig> {
        crate::genesis_config::create_genesis_config(input)
    }

    fn operating_mode(genesis: &Self::GenesisConfig) -> sov_modules_api::OperatingMode {
        genesis.chain_state.operating_mode
    }

    fn wrap_call(
        auth_data: <Self::Auth as TransactionAuthenticator<S>>::Decodable,
    ) -> Self::Decodable {
        match auth_data {
            EvmAndSolanaOffchainAuthenticatorInput::Evm(call) => Self::Decodable::Evm(call),
            EvmAndSolanaOffchainAuthenticatorInput::SolanaOffchain(call)
            | EvmAndSolanaOffchainAuthenticatorInput::Standard(call) => call,
        }
    }

    #[cfg(feature = "native")]
    fn get_transaction_delay_ms(&self, call: &Self::Decodable) -> u64 {
        match call {
            Self::Decodable::SyntheticLoad(
                sov_synthetic_load::CallMessage::RunCPUHeavyOperation { .. },
            ) => 100,
            _ => 0,
        }
    }

    #[cfg(feature = "native")]
    fn populate_pinned_cache(storage: &S::Storage) -> Option<PinnedCache> {
        let buckets_and_limits =
            sov_evm::Evm::<S>::default().get_pinned_cache_buckets_and_limits()?;
        let mut pinned_cache = PinnedCache::default();
        for (bucket_id, limit) in buckets_and_limits {
            use sov_state::pinned_cache::LoadBucketOutcome;

            match pinned_cache.try_load_bucket_if_absent(bucket_id.clone(), storage, limit) {
                Err(e) => {
                    tracing::warn!(bucket_id = ?bucket_id, limit = ?limit, error = ?e, "EVM Failed to load bucket into pinned cache");
                }
                Ok(LoadBucketOutcome::NotSupportedByStorage) => {
                    panic!("EVM Failed to load bucket into pinned cache because the storage doesn't support iteration. This means that pinning is configured but the rollup doesnt support it. Adjust your config or switch to NOMT");
                }
                Ok(LoadBucketOutcome::AlreadyPresent)
                | Ok(LoadBucketOutcome::Loaded)
                | Ok(LoadBucketOutcome::OverSizeLimit) => {} // Explicitly handle each case to force adjustment if other options are added.
            }
        }
        Some(pinned_cache)
    }
}

impl<S: Spec> HasCapabilities<S> for Runtime<S>
where
    S::Address: FromVmAddress<EthereumAddress> + FromVmAddress<Base58Address> + HyperlaneAddress,
{
    type Capabilities<'a> = StandardCapabilities<'a, S, &'a mut sov_paymaster::Paymaster<S>>;
    type SequencingData = sov_modules_api::HDTimestamp;

    fn capabilities(&mut self) -> Guard<Self::Capabilities<'_>> {
        Guard::new(StandardCapabilities {
            bank: &mut self.0.bank,
            gas_payer: &mut self.0.paymaster,
            sequencer_registry: &mut self.0.sequencer_registry,
            accounts: &mut self.0.accounts,
            uniqueness: &mut self.0.uniqueness,
            chain_state: &mut self.0.chain_state,
            operator_incentives: &mut self.0.operator_incentives,
            prover_incentives: &mut self.0.prover_incentives,
            attester_incentives: &mut self.0.attester_incentives,
        })
    }
}

impl<S: Spec> HasKernel<S> for Runtime<S>
where
    S::Address: FromVmAddress<EthereumAddress> + FromVmAddress<Base58Address> + HyperlaneAddress,
{
    type Kernel<'a> = SoftConfirmationsKernel<'a, S>;

    fn inner(&mut self) -> Guard<Self::Kernel<'_>> {
        Guard::new(SoftConfirmationsKernel {
            chain_state: &mut self.0.chain_state,
            blob_storage: &mut self.0.blob_storage,
        })
    }

    #[cfg(feature = "native")]
    fn kernel_with_slot_mapping(&self) -> Arc<dyn KernelWithSlotMapping<S>> {
        Arc::new(self.0.chain_state.clone())
    }
}

impl<S: Spec> EthereumAuthenticator<S> for Runtime<S>
where
    S::Address: FromVmAddress<EthereumAddress> + FromVmAddress<Base58Address> + HyperlaneAddress,
{
    fn add_ethereum_auth(tx: RawTx) -> <Self::Auth as TransactionAuthenticator<S>>::Input {
        EvmAndSolanaOffchainAuthenticatorInput::Evm(tx)
    }
}

impl<S: Spec> SolanaOffchainAuthenticatorTrait<S> for Runtime<S>
where
    S::Address: FromVmAddress<EthereumAddress> + FromVmAddress<Base58Address> + HyperlaneAddress,
{
    fn add_solana_offchain_auth(tx: RawTx) -> <Self::Auth as TransactionAuthenticator<S>>::Input {
        EvmAndSolanaOffchainAuthenticatorInput::SolanaOffchain(tx)
    }
}
