[package]
name = "sov-state"
description = "Defines traits and types for state storage in the Sovereign SDK module system"
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = "Sovereign Permissionless Commercial License"
repository = { workspace = true }

version = { workspace = true }
readme = "README.md"

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
arbitrary = { workspace = true, optional = true }
borsh = { workspace = true, features = ["rc", "bytes"] }
bcs = { workspace = true }
derivative = { workspace = true }
proptest = { workspace = true, optional = true }
serde = { workspace = true, features = ["rc"] }
derive_more = { workspace = true }
serde-big-array = "0.5.1"
sov-rollup-interface = { workspace = true }
sov-universal-wallet = { workspace = true, features = ["macros"] }
sov-db = { workspace = true, optional = true }
hex = { workspace = true }
nomt-core = { workspace = true }
nomt = { workspace = true, optional = true }
sov-metrics = { workspace = true }
tracing = { workspace = true, optional = true }
sov-db-types = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }
test-strategy = { workspace = true }
sha2 = { workspace = true }
serde_json = { workspace = true }
sov-db = { workspace = true, features = ["test-utils"] }
sov-mock-da = { workspace = true, features = ["native"] }
tempfile = { workspace = true }

[features]
arbitrary = [
	"dep:arbitrary",
	"dep:proptest",
	"sov-db?/arbitrary",
	"sov-rollup-interface/arbitrary",
	"sov-db-types/arbitrary",
	"sov-mock-da/arbitrary"
]
bench = []
default = []
native = [
	"sov-db",
	"sov-rollup-interface/native",
	"sov-metrics/native",
	"sov-db-types/native",
	"dep:nomt",
	"dep:tracing",
	"sov-mock-da/native"
]

test-utils = []
