[package]
name = "account_proof_geyser"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib","rlib"]

[dependencies]
borsh = "0.10.3"
serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1.0.86"
solana-geyser-plugin-interface = "=1.16.15"
solana-logger = "=1.16.15"
solana-sdk = "=1.16.15"
solana-transaction-status = "=1.16.15"
solana-runtime = "=1.16.15"
log = "0.4.17"
crossbeam-channel = "0.5.8"
crossbeam = "0.8.2"
blake3 = "1.3.3"
rayon = "1.7.0"
lru = "0.12.0"
anyhow = "1.0.75"
tokio = { version = "1", features = ["full"] }

[dev-dependencies]
rand = "0.8.5"

[workspace]

[profile.release]
debug = true
lto = true
codegen-units = 1
