[package]
name = "sov-rollup-apis"
description = "This crate contains API specification to interact with the gas interface and simulate transactions within the full node"
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

version = { workspace = true }
readme = "README.md"
publish = true

[lints]
workspace = true

[dependencies]
axum = { workspace = true }
borsh = { workspace = true }
thiserror = { workspace = true }
hex = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }

# Sovereign dependencies
sov-rest-utils = { workspace = true }
sov-modules-api = { workspace = true, features = ["native"] }
sov-modules-stf-blueprint = { workspace = true, features = ["native"] }
sov-api-spec = { workspace = true }
sov-rollup-interface = { workspace = true }
sov-rollup-full-node-interface = { workspace = true }
sov-uniqueness = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
axum-server = { workspace = true }
anyhow = { workspace = true }
strum = { workspace = true }
reqwest = { workspace = true }

# Sovereign dependencies
sov-bank = { workspace = true, features = ["native"] }
sov-test-utils = { workspace = true }
sov-kernels = { workspace = true, features = ["native"] }
sov-state = { workspace = true, features = ["native"] }
