[package]
name = "sov-soak-testing-lib"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
publish = false

[dependencies]
tokio = { workspace = true, default-features = false }
borsh = { workspace = true, features = ["derive"] }

schemars = { workspace = true, features = ["derive"] }
serde = { workspace = true, default-features = false, features = [
    "alloc",
    "derive",
] }
anyhow = { workspace = true }
rand = { workspace = true }
clap = { workspace = true }

sov-api-spec = { workspace = true }
sov-transaction-generator = { workspace = true }
sov-modules-api = { workspace = true }
sov-test-utils = { workspace = true, features = ["arbitrary"] }
# modules
sov-value-setter = { workspace = true }
sov-bank = { workspace = true, features = ["native", "arbitrary"] }
sov-synthetic-load = { workspace = true }
sov-test-state-consistency = { workspace = true }
