//! Defines the traits that must be implemented by zkVMs. A zkVM like Risc0 consists of two components,
//! a "guest" and a "host". The guest is the zkVM program itself, and the host is the physical machine on
//! which the zkVM is running. Both the guest and the host are required to implement the [`Zkvm`] trait, in
//! addition to the specialized [`ZkvmGuest`] and [`ZkvmHost`] trait which is appropriate to that environment.
//!
//! For a detailed example showing how to implement these traits, see the
//! [risc0 adapter](https://github.com/Sovereign-Labs/sovereign-sdk/tree/main/adapters/risc0)
//! maintained by the Sovereign Labs team.
pub mod aggregated_proof;
use core::fmt::Debug;

use borsh::{BorshDeserialize, BorshSerialize};
use digest::typenum::U32;
use digest::Digest;
use serde::de::DeserializeOwned;
use serde::{Deserialize, Serialize};
use sov_universal_wallet::UniversalWallet;

use crate as sov_rollup_interface; // Needed for UniversalWallet, as it requires global paths
use crate::crypto::{PublicKey, Signature};
use crate::da::{DaSpec, RelevantBlobs, RelevantProofs};

/// The `CryptoSpec` trait configures the cryptographic primitives used by a particular instance of a rollup.
/// this trait implementation is meant to be provided by the `Zkvm`. module
pub trait CryptoSpec: PartialEq + Debug + Clone + Send + Sync + 'static {
    /// The private key used for digital signatures
    #[cfg(feature = "native")]
    type PrivateKey: crate::crypto::PrivateKey<
        PublicKey = Self::PublicKey,
        Signature = Self::Signature,
    >;

    /// The public key used for digital signatures
    type PublicKey: PublicKey;

    /// The hasher preferred by the rollup, such as Sha256 or Poseidon.
    type Hasher: Digest<OutputSize = U32> + Send + Sync + 'static;

    /// The digital signature scheme used by the rollup.
    type Signature: Signature<PublicKey = Self::PublicKey>
        + serde::Serialize
        + for<'a> serde::Deserialize<'a>;

    /// Get the Sovereign Labs admin public key for this crypto implementation.
    /// This is used in modules like revenue share for admin operations.
    fn sovereign_admin_pubkey() -> Self::PublicKey;
}

/// A complete Zkvm implementation.
pub trait Zkvm: Default + Clone + Send + Sync + 'static {
    /// The verifier for the ZkCircuit
    type Verifier: ZkVerifier;

    /// The guest for the ZkCircuit
    type Guest: ZkvmGuest;

    /// The proof generator. Only available under the `"native"` feature.
    #[cfg(feature = "native")]
    type Host: ZkvmHost<Guest: ZkvmGuest<Verifier = Self::Verifier>>;

    /// Network proving implementation for this Zkvm.
    /// Only available under the `"native"` feature.
    ///
    /// This is an optional component - if the Zkvm does not support network proving, this can be set to `NoopZkvmNetwork<Self::Guest>`,
    /// which is a dummy implementation that cannot be used or constructed.
    #[cfg(feature = "native")]
    type Network: ZkvmNetwork<Guest: ZkvmGuest<Verifier = Self::Verifier>>;
}

/// The arguments required by the [`Zkvm::Host`]'s constructor function.
#[cfg(feature = "native")]
pub type HostArgs<Vm> = <<Vm as Zkvm>::Host as ZkvmHost>::HostArgs;

/// The code commitment for the Zkvm
pub type CodeCommitmentFor<Vm> = <<Vm as Zkvm>::Verifier as ZkVerifier>::CodeCommitment;

/// A serialized inner proof generated by a zkVM prover.
#[derive(Debug, serde::Serialize, serde::Deserialize, Clone)]
pub struct SerializedInnerProof {
    /// The raw bytes of the serialized inner proof.
    pub raw_inner_proof: Vec<u8>,
}

/// A prover instance for a particular Zkvm program/circuit.
pub trait ZkvmHost: Clone + Send + Sync + 'static {
    /// The associated guest type
    type Guest: ZkvmGuest;

    /// The required arguments to the constructor - usually either a `Vec<u8>`` or a path to the file containing an `ELF`.
    #[cfg(feature = "native")]
    type HostArgs: Send + Sync + 'static + Default;

    /// Constructs a new `ZkvmHost`.
    #[cfg(feature = "native")]
    fn from_args(args: &Self::HostArgs) -> Self;

    /// Give the guest a piece of advice non-deterministically
    fn add_hint<T: Serialize>(&mut self, item: T);

    /// Returns a commitment to the program to be proven. This method does a lot of heavy cryptographic work - caller beware!
    #[cfg(feature = "native")]
    fn code_commitment(
        &self,
    ) -> anyhow::Result<<<Self::Guest as ZkvmGuest>::Verifier as ZkVerifier>::CodeCommitment>;

    /// Run the guest in the true zk environment using the provided hints
    /// and generate a SNARK of correct execution.
    fn run(&mut self) -> anyhow::Result<Vec<u8>>;
}

/// A commitment to a zkVM program binary. Every concrete [`ZkVerifier::CodeCommitment`]
/// must implement this so that the commitment can be reduced to a canonical
/// [`CodeCommitmentHash`](aggregated_proof::CodeCommitmentHash) used as the common
/// comparison form across native/zkvm boundaries.
pub trait CodeCommitmentTrait:
    Clone + Debug + Serialize + DeserializeOwned + Send + Sync + PartialEq + Eq
{
    /// Returns the canonical [`CodeCommitmentHash`](aggregated_proof::CodeCommitmentHash)
    /// form of this commitment. Implementations that decode an opaque byte
    /// representation (e.g. SP1's serialized verifying key) may fail if the
    /// bytes are malformed.
    fn to_hash(&self) -> anyhow::Result<aggregated_proof::CodeCommitmentHash>;
}

/// A Zk proof system capable of proving and verifying arbitrary Rust code
/// Must support recursive proofs.
pub trait ZkVerifier: Default + Clone + Send + Sync + 'static {
    /// A commitment to the zkVM program which is being proven
    type CodeCommitment: CodeCommitmentTrait;

    /// Defines the cryptographic operations provided natively by the Zkvm.
    type CryptoSpec: CryptoSpec;

    /// The error type which is returned when a proof fails to verify
    type Error: Debug;

    /// Interpret a sequence of a bytes as a receipt and attempt to verify it against the code commitment.
    /// If the receipt is valid, return a public outputs of the proof.
    fn verify<T: DeserializeOwned>(
        serialized_receipt: &[u8],
        code_commitment: &Self::CodeCommitment,
    ) -> Result<T, Self::Error>;
}

/// A network prover that can submit proofs asynchronously and poll for results.
///
/// Unlike [`ZkvmHost`] which runs proofs synchronously via [`ZkvmHost::run`],
/// a `ZkvmNetwork` submits proof requests to a remote proving service and returns
/// a handle that can be polled for completion. This enables concurrent proof generation
/// across multiple blocks.
#[cfg(feature = "native")]
pub trait ZkvmNetwork: Send + Sync + 'static {
    /// The associated guest type.
    type Guest: ZkvmGuest;

    /// An opaque handle returned by [`ZkvmNetwork::submit`] that identifies a pending proof.
    type ProofHandle: Send + Sync + Clone + core::fmt::Debug + 'static;

    /// Add a hint and submit the proof request in one atomic operation.
    ///
    /// Network proving always generates a real proof.
    /// Returns a [`Self::ProofHandle`] that can be passed to [`ZkvmNetwork::poll`] to check for the result.
    fn add_hint_and_submit<T: Serialize + Send + Sync>(
        &self,
        item: &T,
    ) -> impl core::future::Future<Output = anyhow::Result<Self::ProofHandle>> + Send;

    /// Check whether a previously submitted proof is ready.
    ///
    /// Returns `Ok(Some(proof_bytes))` when the proof is complete,
    /// `Ok(None)` if it is still pending, or an error if proving failed.
    fn poll(
        &self,
        handle: &Self::ProofHandle,
    ) -> impl core::future::Future<Output = anyhow::Result<Option<Vec<u8>>>> + Send;

    /// Returns a commitment to the program being proven.
    ///
    /// This is the verifying key that identifies the guest program and can be
    /// stored at genesis for proof verification.
    fn code_commitment(
        &self,
    ) -> anyhow::Result<<<Self::Guest as ZkvmGuest>::Verifier as ZkVerifier>::CodeCommitment>;
}

/// A no-op [`ZkvmNetwork`] for ZKVMs that don't support network proving.
///
/// This type cannot be constructed because it contains an [`Infallible`](core::convert::Infallible)
/// field. All trait methods use `match self._void {}` to statically prove they are unreachable.
#[cfg(feature = "native")]
pub struct NoopZkvmNetwork<G> {
    _guest: core::marker::PhantomData<G>,
    _void: core::convert::Infallible,
}

#[cfg(feature = "native")]
impl<G: ZkvmGuest + 'static> ZkvmNetwork for NoopZkvmNetwork<G> {
    type Guest = G;
    type ProofHandle = ();

    async fn add_hint_and_submit<T: Serialize + Send + Sync>(
        &self,
        _item: &T,
    ) -> anyhow::Result<Self::ProofHandle> {
        match self._void {}
    }

    async fn poll(&self, _handle: &Self::ProofHandle) -> anyhow::Result<Option<Vec<u8>>> {
        match self._void {}
    }

    fn code_commitment(
        &self,
    ) -> anyhow::Result<<<Self::Guest as ZkvmGuest>::Verifier as ZkVerifier>::CodeCommitment> {
        match self._void {}
    }
}

/// A trait which is accessible from within a zkVM program.
pub trait ZkvmGuest: Send + Sync {
    /// The verifier type associated with this vm.
    type Verifier: ZkVerifier;
    /// Obtain "advice" non-deterministically from the host
    fn read_from_host<T: DeserializeOwned>(&self) -> T;
    /// Add a public output to the zkVM proof
    fn commit<T: Serialize>(&self, item: &T);
}

/// The public output of a SNARK proof in Sovereign, this struct makes a claim that
/// the state of the rollup has transitioned from `initial_state_root` to `final_state_root`.
///
/// The period of time covered by a state transition proof may be a single slot, or a range of slots on the DA layer.
#[derive(
    Clone,
    Debug,
    Serialize,
    Deserialize,
    BorshSerialize,
    BorshDeserialize,
    PartialEq,
    Eq,
    UniversalWallet,
)]
pub struct StateTransitionPublicData<Address, Da: DaSpec, Root> {
    /// The state of the rollup before the transition
    #[borsh(bound(
        serialize = "Root: borsh::ser::BorshSerialize",
        deserialize = "Root: borsh::de::BorshDeserialize"
    ))]
    pub initial_state_root: Root,
    /// The state of the rollup after the transition
    #[borsh(bound(
        serialize = "Root: borsh::ser::BorshSerialize",
        deserialize = "Root: borsh::de::BorshDeserialize"
    ))]
    pub final_state_root: Root,
    /// The slot hash of the state transition
    #[borsh(bound(
        serialize = "<Da as DaSpec>::SlotHash: borsh::ser::BorshSerialize",
        deserialize = "<Da as DaSpec>::SlotHash: borsh::de::BorshDeserialize"
    ))]
    pub slot_hash: Da::SlotHash,

    /// Prover address.
    pub prover_address: Address,
}

#[derive(Serialize, Deserialize, UniversalWallet)]
// Prevent serde from generating spurious trait bounds. The correct serde bounds are already enforced by the
// StateTransitionFunction, DA, and Zkvm traits.
#[serde(bound = "StateRoot: Serialize + DeserializeOwned, Witness: Serialize + DeserializeOwned")]
/// State transition witness.
pub struct StateTransitionWitness<StateRoot, Witness, Da: DaSpec> {
    /// The state root before the state transition
    pub initial_state_root: StateRoot,
    /// The state root after the state transition
    pub final_state_root: StateRoot,
    /// The header of the da block that is being processed
    pub da_block_header: Da::BlockHeader,
    /// Proofs that the relevant blobs belong to the DA block.
    pub relevant_proofs: RelevantProofs<Da::InclusionMultiProof, Da::CompletenessProof>,
    /// The blobs that are being processed
    pub relevant_blobs: RelevantBlobs<<Da as DaSpec>::BlobTransaction>,
    /// The witness for the state transition
    pub witness: Witness,
}

#[derive(Serialize, Deserialize, UniversalWallet)]
#[serde(
    bound = "Address: Serialize + DeserializeOwned, StateRoot: Serialize + DeserializeOwned, Witness: Serialize + DeserializeOwned"
)]
/// Data required to prove a state transition.
pub struct StateTransitionWitnessWithAddress<Address, StateRoot, Witness, Da: DaSpec> {
    /// Witness.
    pub stf_witness: StateTransitionWitness<StateRoot, Witness, Da>,
    /// Prover address.
    pub prover_address: Address,
}
