//! Defines the traits that must be implemented by zkVMs. A zkVM like Risc0 consists of two components,
//! a "guest" and a "host". The guest is the zkVM program itself, and the host is the physical machine on
//! which the zkVM is running. Both the guest and the host are required to implement the [`Zkvm`] trait, in
//! addition to the specialized [`ZkvmGuest`] and [`ZkvmHost`] trait which is appropriate to that environment.
//!
//! For a detailed example showing how to implement these traits, see the
//! [risc0 adapter](https://github.com/Sovereign-Labs/sovereign-sdk/tree/main/adapters/risc0)
//! maintained by the Sovereign Labs team.
pub mod aggregated_proof;
use core::fmt::Debug;

use borsh::{BorshDeserialize, BorshSerialize};
use digest::typenum::U32;
use digest::Digest;
use serde::de::DeserializeOwned;
use serde::{Deserialize, Serialize};
use sov_universal_wallet::UniversalWallet;

use crate::common::SlotNumber;
use crate::crypto::{PublicKey, Signature};
use crate::da::{DaSpec, RelevantBlobs, RelevantProofs};
use crate::zk::aggregated_proof::SerializedAggregatedProof;

/// The `CryptoSpec` trait configures the cryptographic primitives used by a particular instance of a rollup.
/// this trait implementation is meant to be provided by the `Zkvm`. module
pub trait CryptoSpec: PartialEq + Debug + Clone + Send + Sync + 'static {
    /// The private key used for digital signatures
    #[cfg(feature = "native")]
    type PrivateKey: crate::crypto::PrivateKey<
        PublicKey = Self::PublicKey,
        Signature = Self::Signature,
    >;

    /// The public key used for digital signatures
    type PublicKey: PublicKey;

    /// The hasher preferred by the rollup, such as Sha256 or Poseidon.
    type Hasher: Digest<OutputSize = U32> + Send + Sync + 'static;

    /// The digital signature scheme used by the rollup.
    type Signature: Signature<PublicKey = Self::PublicKey>
        + serde::Serialize
        + for<'a> serde::Deserialize<'a>;

    /// Get the Sovereign Labs admin public key for this crypto implementation.
    /// This is used in modules like revenue share for admin operations.
    fn sovereign_admin_pubkey() -> Self::PublicKey;
}

/// A complete Zkvm implementation.
pub trait Zkvm: Default + Clone + Send + Sync + 'static {
    /// The verifier for the ZkCircuit
    type Verifier: ZkVerifier;

    /// The guest for the ZkCircuit
    type Guest: ZkvmGuest;

    /// The proof generator. Only available under the `"native"` feature.
    #[cfg(feature = "native")]
    type Host: ZkvmHost<Guest: ZkvmGuest<Verifier = Self::Verifier>>;

    /// The host responsible for producing outer (aggregation) proofs that
    /// recursively verify one or more inner [`Self::Host`] proofs.
    /// Only available under the `"native"` feature.
    #[cfg(feature = "native")]
    type OuterHost: aggregated_proof::OuterZkvmHost;
}

/// The code commitment for the Zkvm
pub type CodeCommitmentFor<Vm> = <<Vm as Zkvm>::Verifier as ZkVerifier>::CodeCommitment;

/// A serialized proof generated by a zkVM prover.
#[derive(Debug, serde::Serialize, serde::Deserialize, Clone)]
pub struct SerializedZkProof {
    /// The raw bytes of the serialized proof.
    pub raw_proof: Vec<u8>,
}

impl SerializedZkProof {
    /// Length of the serialized proof in bytes.
    pub fn len(&self) -> usize {
        self.raw_proof.len()
    }

    /// Returns `true` if the serialized proof is empty.
    pub fn is_empty(&self) -> bool {
        self.raw_proof.is_empty()
    }
}

/// A prover instance for a particular Zkvm program/circuit.
pub trait ZkvmHost: Clone + Send + Sync + 'static {
    /// The associated guest type
    type Guest: ZkvmGuest;

    /// Returns a commitment to the program to be proven. This method does a lot of heavy cryptographic work - caller beware!
    #[cfg(feature = "native")]
    fn code_commitment(
        &self,
    ) -> anyhow::Result<<<Self::Guest as ZkvmGuest>::Verifier as ZkVerifier>::CodeCommitment>;

    /// Provide a single non-deterministic advice item to the guest and
    /// synchronously generate a SNARK of correct execution over that hint.
    fn add_hint_deferred_and_run<T: Serialize>(
        &mut self,
        item: &T,
        agg_proofs: Vec<SerializedAggregatedProof>,
    ) -> anyhow::Result<SerializedZkProof>;
}

/// A commitment to a zkVM program binary. Every concrete [`ZkVerifier::CodeCommitment`]
/// must implement this so that the commitment can be reduced to a canonical
/// [`CodeCommitmentHash`](aggregated_proof::CodeCommitmentHash) used as the common
/// comparison form across native/zkvm boundaries.
pub trait CodeCommitmentTrait:
    Clone + Debug + Serialize + DeserializeOwned + Send + Sync + PartialEq + Eq
{
    /// Returns the canonical [`CodeCommitmentHash`](aggregated_proof::CodeCommitmentHash)
    /// form of this commitment. Implementations that decode an opaque byte
    /// representation (e.g. SP1's serialized verifying key) may fail if the
    /// bytes are malformed.
    fn to_hash(&self) -> aggregated_proof::CodeCommitmentHash;

    /// Constructs the code commitment from its canonical hash.
    fn from_hash(hash: aggregated_proof::CodeCommitmentHash) -> Self;
}

/// A Zk proof system capable of proving and verifying arbitrary Rust code
/// Must support recursive proofs.
pub trait ZkVerifier: Default + Clone + Send + Sync + 'static {
    /// A commitment to the zkVM program which is being proven
    type CodeCommitment: CodeCommitmentTrait;

    /// Defines the cryptographic operations provided natively by the Zkvm.
    type CryptoSpec: CryptoSpec;

    /// The error type which is returned when a proof fails to verify
    type Error: Debug;

    /// Verifies a proof from inside the zkVM guest.
    ///
    /// The proof itself is not passed as an argument; it is read from the guest
    /// environment (the zkVM's implicit proof input channel). The caller
    /// supplies the serialized public values the proof is expected to commit
    /// to, along with the code commitment identifying which program was
    /// proven.
    #[cfg(target_os = "zkvm")]
    fn verify_with_pub_values<T: DeserializeOwned>(
        pub_values: &aggregated_proof::common::SerializedPubValues,
        code_commitment: &Self::CodeCommitment,
    ) -> Result<T, Self::Error>;

    /// Interpret a sequence of a bytes as a proof and attempt to verify it against the code commitment.
    /// If the proof is valid, return a public outputs of the proof.
    fn verify_with_proof<T: DeserializeOwned>(
        serialized_proof: &SerializedZkProof,
        code_commitment: &Self::CodeCommitment,
    ) -> Result<T, Self::Error>;

    /// Deserialize the claimed public outputs from a serialized proof WITHOUT performing
    /// cryptographic verification.
    ///
    /// The returned value reflects only what the prover *claims* the outputs are. It must
    /// be treated as untrusted until a corresponding [`Self::verify_with_proof`] call
    /// succeeds against an appropriate code commitment. Useful when the caller needs the
    /// claimed outputs to decide which code commitment to verify against (e.g. admin-
    /// initiated rollup upgrades where the verification key itself is being rotated).
    fn extract_public_data<T: DeserializeOwned>(
        serialized_proof: &SerializedZkProof,
    ) -> Result<T, Self::Error>;
}

/// A trait which is accessible from within a zkVM program.
pub trait ZkvmGuest: Send + Sync {
    /// The verifier type associated with this vm.
    type Verifier: ZkVerifier;
    /// Obtain "advice" non-deterministically from the host
    fn read_from_host<T: DeserializeOwned>(&self) -> T;
    /// Add a public output to the zkVM proof
    fn commit<T: Serialize>(&self, item: &T);
}

/// The public output of a SNARK proof in Sovereign, this struct makes a claim that
/// the state of the rollup has transitioned from `initial_state_root` to `final_state_root`.
///
/// The period of time covered by a state transition proof may be a single slot, or a range of slots on the DA layer.
#[derive(
    Clone,
    Debug,
    Serialize,
    Deserialize,
    BorshSerialize,
    BorshDeserialize,
    PartialEq,
    Eq,
    UniversalWallet,
)]
pub struct StateTransitionPublicData<Address, Da: DaSpec, Root> {
    /// The state of the rollup before the transition
    #[borsh(bound(
        serialize = "Root: borsh::ser::BorshSerialize",
        deserialize = "Root: borsh::de::BorshDeserialize"
    ))]
    pub initial_state_root: Root,
    /// The state of the rollup after the transition
    #[borsh(bound(
        serialize = "Root: borsh::ser::BorshSerialize",
        deserialize = "Root: borsh::de::BorshDeserialize"
    ))]
    pub final_state_root: Root,
    /// The canonical slot number of the transition within the rollup's DA fork.
    pub slot_number: SlotNumber,
    /// The slot hash of the state transition
    #[borsh(bound(
        serialize = "<Da as DaSpec>::SlotHash: borsh::ser::BorshSerialize",
        deserialize = "<Da as DaSpec>::SlotHash: borsh::de::BorshDeserialize"
    ))]
    pub slot_hash: Da::SlotHash,

    /// Prover address.
    pub prover_address: Address,
}

#[derive(Serialize, Deserialize, UniversalWallet)]
// Prevent serde from generating spurious trait bounds. The correct serde bounds are already enforced by the
// StateTransitionFunction, DA, and Zkvm traits.
#[serde(bound = "StateRoot: Serialize + DeserializeOwned, Witness: Serialize + DeserializeOwned")]
/// State transition witness.
pub struct StateTransitionWitness<StateRoot, Witness, Da: DaSpec> {
    /// The state root before the state transition
    pub initial_state_root: StateRoot,
    /// The state root after the state transition
    pub final_state_root: StateRoot,
    /// The header of the da block that is being processed
    pub da_block_header: Da::BlockHeader,
    /// Proofs that the relevant blobs belong to the DA block.
    pub relevant_proofs: RelevantProofs<Da::InclusionMultiProof, Da::CompletenessProof>,
    /// The blobs that are being processed
    pub relevant_blobs: RelevantBlobs<<Da as DaSpec>::BlobTransaction>,
    /// The witness for the state transition
    pub witness: Witness,
    /// The canonical slot number of the transition within the rollup's DA fork.
    pub slot_number: SlotNumber,
}

#[derive(Serialize, Deserialize, UniversalWallet)]
#[serde(
    bound = "Address: Serialize + DeserializeOwned, StateRoot: Serialize + DeserializeOwned, Witness: Serialize + DeserializeOwned"
)]
/// Data required to prove a state transition.
pub struct StateTransitionWitnessWithAddress<Address, StateRoot, Witness, Da: DaSpec> {
    /// Witness.
    pub stf_witness: StateTransitionWitness<StateRoot, Witness, Da>,
    /// Prover address.
    pub prover_address: Address,
}
