# A dockerfile for the celestia bridge node in DA layer
# Based on:
# https://github.com/celestiaorg/celestia-node/blob/main/Dockerfile

ARG CELESTIA_NODE_TAG=v0.28.2-mocha

FROM ghcr.io/celestiaorg/celestia-node:${CELESTIA_NODE_TAG} AS celestia-node

FROM docker.io/alpine:3.20.1

ENV CELESTIA_HOME=/root

RUN apk update && \
    apk add --no-cache bash jq curl && \
    wget https://github.com/fullstorydev/grpcurl/releases/download/v1.8.7/grpcurl_1.8.7_linux_x86_64.tar.gz && \
    tar -xvf grpcurl_1.8.7_linux_x86_64.tar.gz && \
    mv grpcurl /usr/local/bin && \
    rm grpcurl_1.8.7_linux_x86_64.tar.gz

# Copy in the binary
COPY --from=celestia-node /bin/celestia /bin/celestia
COPY --from=celestia-node /bin/cel-key /bin/cel-key

COPY ./run-bridge.sh /opt/entrypoint.sh
COPY ./bridge-healthcheck.sh /opt/bridge-healthcheck.sh
RUN chmod +x /opt/entrypoint.sh && chmod +x /opt/bridge-healthcheck.sh

# TODO: Remove it from here, as it depends
HEALTHCHECK --interval=5s --timeout=5s --retries=60 --start-period=60s \
    CMD ["/opt/bridge-healthcheck.sh", "/credentials/bridge-0.jwt"]

EXPOSE 2121 26658

CMD ["/opt/entrypoint.sh"]
