# A dockerfile for the celestia validator in consensus layer
# Based on:
# https://github.com/celestiaorg/celestia-app/blob/main/Dockerfile

ARG CELESTIA_APP_TAG=v7.0.2-mocha

FROM ghcr.io/celestiaorg/celestia-app:${CELESTIA_APP_TAG} AS celestia-app

FROM docker.io/alpine:3.23

ENV CELESTIA_HOME=/root

RUN apk add --no-cache bash jq curl dasel && \
    wget -O /tmp/grpcurl.tar.gz https://github.com/fullstorydev/grpcurl/releases/download/v1.9.3/grpcurl_1.9.3_linux_x86_64.tar.gz && \
    tar -xf /tmp/grpcurl.tar.gz -C /usr/local/bin grpcurl && \
    rm /tmp/grpcurl.tar.gz

# Copy in the binary
COPY --from=celestia-app /bin/celestia-appd /bin/celestia-appd

COPY ./run-validator.sh /opt/entrypoint.sh
COPY ./validator-healthcheck.sh /opt/validator-healthcheck.sh
RUN chmod +x /opt/entrypoint.sh /opt/validator-healthcheck.sh

# https://docs.docker.com/reference/dockerfile/#healthcheck
HEALTHCHECK --interval=10s --timeout=5s --retries=30 --start-period=10s \
    CMD ["/opt/validator-healthcheck.sh"]

# p2p, rpc and prometheus port
EXPOSE 26656 26657 1317 9090

CMD ["/opt/entrypoint.sh"]
