# A dockerfile for the celestia bridge node in DA layer
# Based on:
# https://github.com/celestiaorg/celestia-node/blob/main/Dockerfile

ARG CELESTIA_NODE_TAG=v0.29.1-mocha

FROM ghcr.io/celestiaorg/celestia-node:${CELESTIA_NODE_TAG} AS celestia-node

FROM docker.io/alpine:3.23

ENV CELESTIA_HOME=/root

RUN apk add --no-cache bash jq curl && \
    wget -O /tmp/grpcurl.tar.gz https://github.com/fullstorydev/grpcurl/releases/download/v1.9.3/grpcurl_1.9.3_linux_x86_64.tar.gz && \
    tar -xf /tmp/grpcurl.tar.gz -C /usr/local/bin grpcurl && \
    rm /tmp/grpcurl.tar.gz

# Copy in the binary
COPY --from=celestia-node /bin/celestia /bin/celestia
COPY --from=celestia-node /bin/cel-key /bin/cel-key

COPY ./run-bridge.sh /opt/entrypoint.sh
COPY ./bridge-healthcheck.sh /opt/bridge-healthcheck.sh
RUN chmod +x /opt/entrypoint.sh && chmod +x /opt/bridge-healthcheck.sh

HEALTHCHECK --interval=5s --timeout=5s --retries=60 --start-period=60s \
    CMD ["/opt/bridge-healthcheck.sh"]

EXPOSE 2121 26658

CMD ["/opt/entrypoint.sh"]
