//! A [`jsonrpsee`] client for interacting with the Sovereign SDK ledger
//! JSON-RPC API.
//!
//! See [`RpcClient`].

use jsonrpsee::proc_macros::rpc;
use sov_rollup_interface::rpc::{BatchIdentifier, QueryMode, SlotIdentifier, TxIdentifier};
use sov_rollup_interface::stf::Event;

use crate::HexHash;

/// A [`jsonrpsee`] trait for interacting with the ledger JSON-RPC API.
///
/// Client and server implementations are automatically generated by
/// [`jsonrpsee`], see [`RpcClient`] and [`RpcServer`].
///
/// For more information about the specific methods, see the
/// [`sov_rollup_interface::rpc`] module.
///
/// TODO: `getEvents`, which has a `Vec<T>` as a single parameter. That's not
/// supported by `jsonrpsee`, surprisingly.
#[rpc(client, namespace = "ledger")]
pub trait Rpc<Slot, Batch, Tx>
where
    Slot: serde::Serialize,
    Batch: serde::Serialize,
    Tx: serde::Serialize,
{
    #[method(name = "getSlots")]
    async fn get_slots(
        &self,
        slot_ids: Vec<SlotIdentifier>,
        query_mode: QueryMode,
    ) -> RpcResult<Vec<Option<Slot>>>;

    #[method(name = "getBatches")]
    async fn get_batches(
        &self,
        batch_ids: Vec<BatchIdentifier>,
        query_mode: QueryMode,
    ) -> RpcResult<Vec<Option<Batch>>>;

    #[method(name = "getTransactions")]
    async fn get_transactions(
        &self,
        transaction_ids: Vec<TxIdentifier>,
        query_mode: QueryMode,
    ) -> RpcResult<Vec<Option<Tx>>>;

    #[method(name = "getHead")]
    async fn get_head(&self, query_mode: QueryMode) -> RpcResult<Option<Slot>>;

    #[method(name = "getSlotByHash")]
    async fn get_slot_by_hash(
        &self,
        hex_hash: HexHash,
        query_mode: QueryMode,
    ) -> RpcResult<Option<Slot>>;

    #[method(name = "getBatchByHash")]
    async fn get_batch_by_hash(
        &self,
        hex_hash: HexHash,
        query_mode: QueryMode,
    ) -> RpcResult<Option<Batch>>;

    #[method(name = "getTransactionByHash")]
    async fn get_tx_by_hash(
        &self,
        hex_hash: HexHash,
        query_mode: QueryMode,
    ) -> RpcResult<Option<Tx>>;

    #[method(name = "getSlotByNumber")]
    async fn get_slot_by_number(
        &self,
        number: u64,
        query_mode: QueryMode,
    ) -> RpcResult<Option<Slot>>;

    #[method(name = "getBatchByNumber")]
    async fn get_batch_by_number(
        &self,
        number: u64,
        query_mode: QueryMode,
    ) -> RpcResult<Option<Batch>>;

    #[method(name = "getTransactionByNumber")]
    async fn get_tx_by_number(&self, number: u64, query_mode: QueryMode) -> RpcResult<Option<Tx>>;

    #[method(name = "getEventByNumber")]
    async fn get_event_by_number(&self, number: u64) -> RpcResult<Option<Event>>;

    #[method(name = "getSlotsRange")]
    async fn get_slots_range(
        &self,
        start: u64,
        end: u64,
        query_mode: QueryMode,
    ) -> RpcResult<Vec<Option<Slot>>>;

    #[method(name = "getBatchesRange")]
    async fn get_batches_range(
        &self,
        start: u64,
        end: u64,
        query_mode: QueryMode,
    ) -> RpcResult<Vec<Option<Batch>>>;

    #[method(name = "getTransactionsRange")]
    async fn get_txs_range(
        &self,
        start: u64,
        end: u64,
        query_mode: QueryMode,
    ) -> RpcResult<Vec<Option<Tx>>>;

    #[subscription(name = "subscribeSlots", item = u64)]
    async fn subscribe_slots(&self) -> SubscriptionResult;
}
