[package]
name = "sov-demo-prover-guest"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
anyhow = "1.0.68"
presence = { path = "../../../../adapters/avail", default-features = false, features = ["verifier"] }
risc0-zkvm = { version = "0.16", default-features = false, features = ["std"] }
borsh = { version = "0.10.3", features = ["bytes"] }
demo-stf = { path = "../../../demo-stf" }
const-rollup-config = { path = "../../../const-rollup-config" }
sov-rollup-interface = { path = "../../../../rollup-interface" }
risc0-adapter = { path = "../../../../adapters/risc0", default-features = false }

# TODO: Just for test
tracing = "0.1.37"
log = "0.4.17"

[build-dependencies]
directories = "5.0"
downloader = "0.2"
serde = { version = "1.0", default-features = false, features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10.6"
tempfile = "3.5"
zip = "0.6"

[profile.dev]
opt-level = 3

[profile.dev.build-override]
opt-level = 3

[profile.release]
debug = 1
lto = true

[profile.release.build-override]
opt-level = 3
