[package]
name = "sov-eth-dev-signer"
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

version = { workspace = true }
readme = "README.md"
publish = false

[lints]
workspace = true

[dependencies]
thiserror = { workspace = true }
alloy-consensus = { workspace = true, features = ["secp256k1"] }
alloy-primitives = { workspace = true }
secp256k1 = { workspace = true }
