use demo_stf::runtime::Runtime;
use sov_address::MultiAddressEvm;
use sov_mock_da::MockDaSpec;
use sov_mock_zkvm::MockZkvm;
use sov_modules_api::execution_mode::Native;
use sov_zkvm_utils::should_skip_guest_build;

fn main() -> anyhow::Result<()> {
    println!("cargo::rerun-if-env-changed=SKIP_GUEST_BUILD");
    println!("cargo::rerun-if-env-changed=SOV_PROVER_MODE");
    println!("cargo::rustc-check-cfg=cfg(skip_guest_build)");
    println!("cargo:rerun-if-changed=NULL");

    // It will be true only if SKIP_GUEST_BUILD is 1 or true
    if should_skip_guest_build("any-zkvm") {
        println!("cargo::rustc-cfg=skip_guest_build");
    }

    type S = sov_modules_api::configurable_spec::ConfigurableSpec<
        MockDaSpec,
        MockZkvm,
        MockZkvm,
        MultiAddressEvm,
        Native,
    >;

    sov_build::Options::builder()
        .rust_autogenerated_path("autogenerated.rs")
        .set_git_hash(true)
        .json_schema(false)
        .build()
        .apply::<S, Runtime<S>>()
}
