name: Release (TypeScript)

on:
  push:
    branches: ["nightly"]
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to run the workflow on"
        required: false
        default: "dev"

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions: {}
jobs:
  release:
    # prevents this action from running on forks
    if: github.repository == 'Sovereign-Labs/sovereign-sdk'
    permissions:
      contents: write # to create release (changesets/action)
      id-token: write # OpenID Connect token needed for provenance
      pull-requests: write # to create pull request (changesets/action)
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch || '' }}
      - uses: pnpm/action-setup@v4
        with:
          package_json_file: ./typescript/package.json
      - uses: actions/setup-node@v6
        with:
          node-version: 20.x
          cache: "pnpm"
          cache-dependency-path: "./typescript/pnpm-lock.yaml"
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.5
      - name: Install dependencies
        run: pnpm install
        working-directory: ./typescript
      - name: Build
        run: pnpm build
        working-directory: ./typescript
      - name: Run Tests
        run: pnpm test
        working-directory: ./typescript
      - name: Hacky symlink
        run: |
          ln -s typescript/package.json package.json
          ln -s typescript/pnpm-lock.yaml pnpm-lock.yaml
          ln -s typescript/.changeset .changeset
      - name: Create Release Pull Request or Publish to npm
        uses: changesets/action@v1
        with:
          publish: pnpm --dir ./typescript release
          version: pnpm --dir ./typescript pkg-version
          cwd: ./typescript
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
